### ISSUE TITLE
What is the license of this project?

### ISSUE THREAD

**Issue by hofingermarkus** [noahzn/Lite-Mono#1]
Hi,

cool work, and thanks for releasing the code!
What is the license of this project? Is it MIT like [EPC-Depth](https://github.com/prstrive/EPCDepth), or something like Apache 2.0 as in the [monocular depth toolbox](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox) or something else?

Best regards,
Markus

**Comment by noahzn** [comment]
Hi Markus,

Thank you for your interest in our work. I have updated the license.

**Comment by hofingermarkus** [comment]
Thank you :)
