### ISSUE TITLE
A little problem

### ISSUE THREAD

**Issue by DongyangHuLi** [noahzn/Lite-Mono#10]
Hi~, noahzn

May I ask how you get the intrinsics 'K' of your camera?
self.K = np.array([[0.58, 0, 0.5, 0],
                       [0, 1.92, 0.5, 0],
                       [0, 0, 1, 0],
                       [0, 0, 0, 1]], dtype=np.float32)
Bests,
Hu Li.

**Comment by DongyangHuLi** [comment]
> Hi, The intrinsics matrix is the same as that used in Monodepth2. It is calculated by averaging the intrinsics of all the images. [See this link](https://github.com/nianticlabs/monodepth2/blob/master/datasets/kitti_dataset.py#L29), and [this link](https://github.com/nianticlabs/monodepth2/issues/308)

Thank you for your prompt reply!
I'm still confused about the reason for this. Why not just read the intrinsic of each image instead of averaging all the images?

**Comment by noahzn** [comment]
@DongyangHuLi Please check this [issue](https://github.com/nianticlabs/monodepth2/issues/73).
