### ISSUE TITLE
关于训练lite-mono-8m-pretrain.pth参数尺寸不匹配

### ISSUE THREAD

**Issue by chaoying0115** [noahzn/Lite-Mono#101]
您好，非常感谢您们出色的成果。在预训练lite-mono-8m-pretrain时出现以下错误，想请问有何解决方式，非常期待得到指导，提前致谢！
执行“python train.py --data_path /data/ccy/project/Lite-Mono-main/kitti_data/  --model_name mytrain --num_epochs 30 --batch_size 12 --mypretrain /data/ccy/project/Lite-Mono-main/lite-mono-8m-pretrain.pth  --lr 0.0001 5e-6 31 0.0001 1e-5 31”
![1](https://github.com/noahzn/Lite-Mono/assets/46865317/3059eb2c-f122-46cc-a0ef-46090987dc5f)
![2](https://github.com/noahzn/Lite-Mono/assets/46865317/4ec8e0da-1628-456a-83d1-fc14d7acad4a)

**Comment by noahzn** [comment]
你好，感谢你对我们工作的关注。如果使用lite-mono-8m模型，你需要增加一个参数`--model lite-mono-8m`，默认构建的模型是`lite-mono`。
