### ISSUE TITLE
关于不使用Imagenet预训练模型进行训练。

### ISSUE THREAD

**Issue by Rookie764** [noahzn/Lite-Mono#102]
作者您好，最近我在跟着您的论文中的参数设置进行复现，非常感谢提供的训练代码。
但是我一直不能复现比较接近的结果。
以下是我最近复现的结果：
参数设置：
● drop_path:0.3
● batch_size:9
● lr:
● 0: 0.0005
● 1: 0.000005
● 2: 35
● 3: 0.0005
● 4: 0.00001
● 5: 35
● num_epochs: 35 
● num_workers: 12
以下是后几轮的结果：
epoch29:
![image](https://github.com/noahzn/Lite-Mono/assets/98649891/9b171ed0-ec75-498d-a5c5-828ccd694f6f)
epoch30:
![image](https://github.com/noahzn/Lite-Mono/assets/98649891/56887a36-72cb-4070-8f03-f556ffede76f)
epoch31:
![image](https://github.com/noahzn/Lite-Mono/assets/98649891/e30145af-5ac7-469c-890c-2036cb727a4d)

我的几点疑问如下：
1. 由于设备的问题，我是在2080上进行的实验，所以batchsize改小了一点，这个影响很大吗？
2. 我也是使用了ChainedScheduler进行学习率衰减，但效果相差太多了，请问有其他的设置吗？

**Comment by Rookie764** [comment]
> 你好，如果不使用预训练模型的话，你的第二张图的结果已经超过了我论文中报告的结果。

非常感谢你的回复，我发现是自己比较错了结果。
我看了看之前的issues，发现你提供过一些在ImageNet上预训练的情况，之后我再去看一些这方面的训练。
十分感谢！

**Comment by Rookie764** [comment]
这几天我尝试了一下利用Imagenet进行预训练，效果还不错，但是达不到你在之前的issue里提到的精度，请问能给我发一份你的预训练代码。

**Comment by noahzn** [comment]
你是指在Imagenet预训练还是使用预训练过的模型训练Lite-Mono？

**Comment by Rookie764** [comment]
在Imagenet预训练

**Comment by Rookie764** [comment]
作者你好，是有关imagenet预训练的部分👀

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月10日(周日) 晚上11:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [noahzn/Lite-Mono] 关于不使用Imagenet预训练模型进行训练。 (Issue #102)




 
你是指在Imagenet预训练还是使用预训练过的模型训练Lite-Mono？

**Comment by noahzn** [comment]
你留个邮箱给我

**Comment by Rookie764** [comment]
> 你留个邮箱给我

954442870@qq.com
非常感谢🥳

**Comment by FFDoube** [comment]
作者你好，我也想要一份imagenet预训练部分的代码，谢谢
120679242@qq.com
然后我想知道预训练时输入的图片尺寸是多少，224x224吗？

**Comment by lai-pf** [comment]
我也想要一份imagenet预训练部分的代码，拜托了谢谢
邮箱2539317645@qq.com

**Comment by YIMings139** [comment]
作者在readme公布了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月9日(周二) 上午10:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [noahzn/Lite-Mono] 关于不使用Imagenet预训练模型进行训练。 (Issue #102)




 
我也想要一份imagenet预训练部分的代码，拜托了谢谢
 ***@***.***

**Comment by lai-pf** [comment]
> 作者在readme公布了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年1月9日(周二) 上午10:53 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [noahzn/Lite-Mono] 关于不使用Imagenet预训练模型进行训练。 (Issue #102) 我也想要一份imagenet预训练部分的代码，拜托了谢谢 ***@***.*** — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

感谢回复 我看到了该预训练代码repo 谢谢
