### ISSUE TITLE
about pretainmodel 

### ISSUE THREAD

**Issue by yinyang472** [noahzn/Lite-Mono#104]
do you have pretainmodel 320*1024 thanks

**Comment by noahzn** [comment]
Hi, the pre-trained models are resolution agnostic. So, you just need to download the pre-trained model for a specific lite-mono model (small, 8m, etc.)

**Comment by yinyang472** [comment]
我有一个问题不太清楚 想和您请教一下  预训练模型输入的大小会影响后续训练时的精度么
