### ISSUE TITLE
如何让模型适配鱼眼图片呢？

### ISSUE THREAD

**Issue by Linkersem** [noahzn/Lite-Mono#105]
您好，我想请问一下我能否直接用鱼眼图片训练来使模型能够对鱼眼图片进行深度预测呢？

**Comment by noahzn** [comment]
你好，我没有试过使用鱼眼图片，但是我觉得整体方法是可行。只是可能鱼眼图像有较大的图像畸变需要处理，而且应该需要对代码中的图像重建部分进行调整以使鱼眼图像能够顺利重建。

**Comment by Linkersem** [comment]
谢谢您的回复，能麻烦您展开讲一下”对代码中的图像重建部分进行调整以使鱼眼图像能够顺利重建。“这一部分的思想或者逻辑吗？这一部分我没有get到

**Comment by noahzn** [comment]
Lite-Mono是基于Monodepth2的，将深度估计转换为图像重建任务并优化loss。你要自己测试一下那部分代码能不能直接用在你的鱼眼图像上。

**Comment by noahzn** [comment]
I am now closing this issue due to a lack of response.
