### ISSUE TITLE
关于数据预处理问题

### ISSUE THREAD

**Issue by dsfdwsfsdf** [noahzn/Lite-Mono#106]
您好！在readme.txt中说是数据集预处理可以参考“Monodepth2"这篇文章的预处理方式，但是我看Monodepth2使用的是Zhou的分割，您使用的是Eigen的分割，请问是需要在数据预处理的时候将"wget -i splits/kitti_archives_to_download.txt -P kitti_data/"中的路径换成这篇文章中的“test_files.txt”吗？

**Comment by noahzn** [comment]
你好，训练使用的是`eigen_zhou`，测试使用的是`eigen`， 和Monodepth2一样的。

**Comment by dsfdwsfsdf** [comment]
> 你好，训练使用的是`eigen_zhou`，测试使用的是`eigen`， 和Monodepth2一样的。

好的，谢谢！
