### ISSUE TITLE
What are the environmental requirements of the project

### ISSUE THREAD

**Issue by zzhmx** [noahzn/Lite-Mono#107]
I encountered an error while running the training program：
AttributeError: module 'torchvision.models.resnet' has no attribute 'model_urls'
Can you tell me the environmental requirements of the project.

**Comment by noahzn** [comment]
Hi, please check the versions of dependencies [here](https://github.com/noahzn/Lite-Mono/issues/58).

**Comment by noahzn** [comment]
I am now closing this issue due to a lack of response.
