### ISSUE TITLE
关于在imageNet上的预训练方法

### ISSUE THREAD

**Issue by FFDoube** [noahzn/Lite-Mono#108]
作者您好，我最近在学习并尝试复现您的工作
我想知道在imageNet上进行预训练的话，depth_encoder部分的pipeline有改动吗？
还是说仅仅是把CDC和LGFI模块放到其他常用的图像识别框架下训练
因为我发现您在stem层使用了3次的BN，对于较大的imageNet可以改为LN或者减少norm层吗
如果方便的话能否给我一份您imageNet上的预训练代码，非常感谢！！！
120679242@qq.com

**Comment by noahzn** [comment]
你好，请拉取最新的commit，已经包含了预训练代码。

**Comment by FFDoube** [comment]
> 你好，请拉取最新的commit，已经包含了预训练代码。

看到了，非常感谢，辛苦了！！
