### ISSUE TITLE
training log

### ISSUE THREAD

**Issue by DongyangHuLi** [noahzn/Lite-Mono#11]
Hi, noahzn
     Could you provide training logs?
     When I was training, I didn't know why there was a problem with the predicted rgb:
![image](https://user-images.githubusercontent.com/116615779/231331028-0c19969f-0dad-4ab0-a804-1c925865de57.png)
     Can you give me some help? Thank you very much!

**Comment by DongyangHuLi** [comment]
In the case above where I changed the camera intrinsics to real intrinsics , when I used the parameters provided in the code, it became like this, I wonder why they have this difference,
![image](https://user-images.githubusercontent.com/116615779/231337017-4c21de82-aae0-4463-bae7-8c2d1f980a5c.png)

**Comment by deansaice** [comment]
I seem like to meet the same problem with your first four pictures, could you share me with the problem that you fould about it？

**Comment by DongyangHuLi** [comment]
> I seem like to meet the same problem with your first four pictures, could you share me with the problem that you fould about it？
Hey, my problem is that the intrinsic parameters are set incorrectly. You can check your intrinsic parameters.
