### ISSUE TITLE
关于提供tiny-litemomo在imageNet上的预训练参数。

### ISSUE THREAD

**Issue by zhenzhenzhizhi** [noahzn/Lite-Mono#110]
非常感谢作者的贡献，我很想将你的结构设计用作我辅助任务深度估计的网络结构，但是我不需要那么深的网络结构，因为我的输入才120*120.所以只需要tiny版本的预训练版本即可。
所以作者能否提供一下tiny-litemomo在imageNet上的预训练权重。非常感谢！

**Comment by noahzn** [comment]
你好，请下载[此文件](https://surfdrive.surf.nl/files/index.php/s/I4Mgih3uAvGkhTd)，但是我不确定这个预训练参数是不是用于最终论文中tiny实验结果的权重，你可以载入训练2-3个epochs看看大致效果。
