### ISSUE TITLE
关于pose的模型权重

### ISSUE THREAD

**Issue by Augusthyq** [noahzn/Lite-Mono#111]
非常感谢作者的贡献，请问作者能否提供一下litemono8m最终的pose训练模型。非常感谢！

**Comment by noahzn** [comment]
Hi, here is the [download link](https://surfdrive.surf.nl/files/index.php/s/cxunvpcDeVu4jzx).

**Comment by Augusthyq** [comment]
> Hi, here is the [download link](https://surfdrive.surf.nl/files/index.php/s/cxunvpcDeVu4jzx).

Oh,very thanks.
