### ISSUE TITLE
A runtimeerror occured 

### ISSUE THREAD

**Issue by cz0708** [noahzn/Lite-Mono#114]
There is a runtimeerror when i run test_simple.py or evaluate_depth.py, i donot know what exactly wrong, and my torch==2.1.2+cu118
![1705458342181](https://github.com/noahzn/Lite-Mono/assets/57240821/ca09faa8-557b-4d7a-b835-7af92719a26e)

**Comment by noahzn** [comment]
Please make sure that you load the correct checkpoint.

**Comment by cz0708** [comment]
Yes, tried the checkpoints, not every one can work

**Comment by noahzn** [comment]
Obviously this is a mismatch between the checkpoint and the model you are using. What arguments did you use to run the script?

**Comment by cz0708** [comment]
Ohhhhh no, I forgot set --model, thanks for your sincerely help
