### ISSUE TITLE
the eval file about 'gt_depths.npz'

### ISSUE THREAD

**Issue by sunny-zzw** [noahzn/Lite-Mono#115]
First of all thank you for your work, I would like to ask if you can provide 'gt_depths.npz' in 'evaluate_dept. py', or where can I go to download this file, thank you again

**Comment by noahzn** [comment]
Hi, please follow this [link](https://github.com/noahzn/Lite-Mono/issues/26).

**Comment by sunny-zzw** [comment]
Thank you for your reply. I only saw the npy file, not the npz file. Could you please provide further help, thanks a lot again

**Comment by noahzn** [comment]
Hi, the steps are in the link I posted above. Please read it carefully to export the ground truth.

**Comment by sunny-zzw** [comment]
Thanks a lot , i got it
