### ISSUE TITLE
about checkpoint

### ISSUE THREAD

**Issue by SooHyunHub** [noahzn/Lite-Mono#117]
Hello, author
I don't have the resources to use your repo, so I'm trying to learn from colab. I want to use checkpoints to continue learning where I left off. But I've been looking for it for a day and it still seems very difficult for me. I would be very grateful if you could answer me. Thank you for checking

**Comment by noahzn** [comment]
Hi, thank you for your interest in our work. On the homepage of our repo you can find a [table](https://github.com/noahzn/Lite-Mono?tab=readme-ov-file#kitti). You can download all the checkpoints in the first column, and you can also download the weights pre-trained on ImageNet in the third column. Just click on the underlined blue text.

**Comment by noahzn** [comment]
I'm closing this issue now.
