### ISSUE TITLE
retrain

### ISSUE THREAD

**Issue by haifengwu205** [noahzn/Lite-Mono#118]
Hi, I retrain your coder, however, some of the metrics dropped significantly. The following are the results of my retraining. sq_rel and rmse dropped significantly. I didn't modify any parameters, why is this happening?

#    abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
# &   0.107  &   0.805  &   4.591  &   0.183  &   0.889  &   0.962  &   0.983  \\

**Comment by noahzn** [comment]
Hi, how did you evaluate the training? Did you only evaluate on the last epoch?
There are some discussions regarding the reproducibility. 
https://github.com/noahzn/Lite-Mono/issues/7
https://github.com/noahzn/Lite-Mono/issues/4

**Comment by noahzn** [comment]
I'm closing this issue now.
