### ISSUE TITLE
PoseNet pretrained weights

### ISSUE THREAD

**Issue by maxvandenhoven** [noahzn/Lite-Mono#119]
Hi @noahzn, thank you for releasing the code for this paper! Would it be possible to share the pretrained weights of the pose networks? Currently, only the pretrained weights of the depth networks are provided. Thank you!

**Comment by noahzn** [comment]
Hi, here are some related issues and you can download the weights.
https://github.com/noahzn/Lite-Mono/issues/111
https://github.com/noahzn/Lite-Mono/issues/92
https://github.com/noahzn/Lite-Mono/issues/65

**Comment by maxvandenhoven** [comment]
Thank you!
