### ISSUE TITLE
 size mismatch for downsample_layers......

### ISSUE THREAD

**Issue by lyx323** [noahzn/Lite-Mono#12]
hi:
when i run with " python test_simple.py --load_weights_folder ./model/ --image_path ./indoor/", i got mistake like " Missing key(s) in state_dict: "stages.2.6.ddwconv.conv.weight", ...... size mismatch for downsample_layers.0.0.conv.weight:....",and i download the weight " lite-mono-tiny". Then all of the model i have tried and got same erorr.
 how can i fix this, thank you so much!

**Comment by noahzn** [comment]
Hi, the default model used in `test_simple.py` is `lite-mono`. if you want to load the weights of `lite-mono-tiny` you should also indicate `--model lite-mono-tiny`

**Comment by lyx323** [comment]
已收到

**Comment by lyx323** [comment]
> Hi, the default model used in `test_simple.py` is `lite-mono`. if you want to load the weights of `lite-mono-tiny` you should also indicate `--model lite-mono-tiny`

thanks  a lot！
