### ISSUE TITLE
where is requirements.txt?how to export onnx and trt?

### ISSUE THREAD

**Issue by SoulProficiency** [noahzn/Lite-Mono#120]

**Comment by noahzn** [comment]
Hi, the requirements are [here](https://github.com/noahzn/Lite-Mono/issues/58). 
Regarding the conversion of the model to ONNX and TRT you can check some tutorials and they are not included in this repo.

**Comment by SoulProficiency** [comment]
> Hi, the requirements are [here](https://github.com/noahzn/Lite-Mono/issues/58). Regarding the conversion of the model to ONNX and TRT you can check some tutorials and they are not included in this repo.

thanks a lot
