### ISSUE TITLE
CDilated weird ddconv weight shape

### ISSUE THREAD

**Issue by maxvandenhoven** [noahzn/Lite-Mono#121]
Hi @noahzn,

When loading the pretrained weights for the depth encoder, I noticed that the dilated convolution layer has an unexpected shape:

stages.0.0.ddwconv.conv.weight has shape torch.Size([48, 1, 3, 3]), where I would expect it to have shape torch.Size([48, 48, 3, 3]), since the number of channels stays the same in DilatedConv. Do you have any insight on why this is the case?

Thanks!

**Comment by noahzn** [comment]
Hi, please make sure you are using the correct pre-trained weights and model. You can change the model using `--model`.

**Comment by maxvandenhoven** [comment]
I am loading the .pth directly with `torch.load` for inspection, that is how I noticed.

**Comment by noahzn** [comment]
Could you load the decoder using my code to see if it works or not?

**Comment by maxvandenhoven** [comment]
I did some further investigation, and it turns out the dimension of 1 for the kernel is due to the use of groups in the dilated convolution. The code works fine, but I was curious why the kernel weight was shaped like that. Thanks!
