### ISSUE TITLE
about Make3D result

### ISSUE THREAD

**Issue by sunny-zzw** [noahzn/Lite-Mono#122]
Happy New Year First!  Could you provide me the input image of Make3D(Fig.5  Qualitative results), or the path of those input images, thank you a lot

**Comment by noahzn** [comment]
Hi, you can download on their website http://make3d.cs.cornell.edu/data.html

**Comment by noahzn** [comment]
Hi, I didn't keep the information on Make3D. Therefore, I cannot give you the filenames of these pictures. Make3D's test set only has 134 images, so it's also doable to find these images manually.

**Comment by sunny-zzw** [comment]
Thanks, i looked for those in 134 images, but only find one, i will look for those carefully again

**Comment by noahzn** [comment]
I am now closing this issue. Feel free to reopen it or create a new one if you have more questions.
