### ISSUE TITLE
How to get absolute distances on your own dataset?

### ISSUE THREAD

**Issue by lDarryll** [noahzn/Lite-Mono#123]
Hi author, If I collect some data by myself (including depth information labels), how can I get the absolute depth distance on your project?

**Comment by noahzn** [comment]
Hi, the method itself is to generate relative depth values. If you have metric depth values, you might try scaling the relative depth values using a scaling factor. But the result might be not accurate enough.

**Comment by lDarryll** [comment]
I am a newbie, how should I calculate the scale factor(base my own dataset), can you tell me where is the code to calculate the scale factor or tell me how to calculate the scale factor, thank you very much!

**Comment by noahzn** [comment]
Hi, I don't have this code. The question is out of the scope of this repo. 
[Median scaling](https://github.com/noahzn/Lite-Mono/blob/4874b35df8ed4da16159ce8be8c697028b72bf76/evaluate_depth.py#L170) might be a good starting point to your question.

**Comment by lDarryll** [comment]
Is it possible to refer to this part of the code to statistically calculate the scaling factor that corresponds to my own data.
![image](https://github.com/noahzn/Lite-Mono/assets/34019070/84c1d61a-e328-49bd-b3ff-590b0eeca326)

**Comment by noahzn** [comment]
Yes, you can have a try, but it might not be accurate enough.

**Comment by lDarryll** [comment]
So when doing model inference I don't have a depth of gt then I can't calculate the absolute distance? In other words, this scaling factor can only be calculated when doing evaluation.

**Comment by noahzn** [comment]
If you don't have the ground-truth then you cannot use this median scaling.

**Comment by lDarryll** [comment]
Okay, I got it. Thanks.
