### ISSUE TITLE
Query: Retrieving Depth Values Instead of Depth Map Images

### ISSUE THREAD

**Issue by sonainjameel** [noahzn/Lite-Mono#125]
Hello,

I've been exploring the functionality of the trained models provided in this repository and have successfully used the following command for testing:

`python test_simple.py --load_weights_folder path/to/your/weights/folder --image_path path/to/your/test/image`

This command outputs the depth map as an image file. However, for my specific use case, I'm interested in obtaining the raw depth values directly, rather than in image format. Is there a way to modify the command or the script to output depth values (e.g., in a CSV or JSON file) instead of, or in addition to, the depth map images?

Any guidance or suggestions on how to achieve this would be greatly appreciated.

Thank you for your time and the great work on this project!

**Comment by noahzn** [comment]
Hi, in `test_simple.py`the saving function has already been implemented. Please take a look these [two lines](https://github.com/noahzn/Lite-Mono/blob/main/test_simple.py#L167-L168).

**Comment by sonainjameel** [comment]
Thank you for pointing me towards the saving function in `test_simple.py` and highlighting the relevant lines. I appreciate your guidance! I'll dive deeper into this and if any questions arise in the process, I'll be sure to reach out. Thanks again for your help!
