### ISSUE TITLE
what's the shape of the input batch when training?

### ISSUE THREAD

**Issue by renyuanzhe** [noahzn/Lite-Mono#126]
Is it something like [batch_size, sequence length, h ,w ,3]?

**Comment by noahzn** [comment]
The shape is [batch_size, C, H, W]

**Comment by renyuanzhe** [comment]
> The shape is [batch_size, C, H, W]

Doesn't it need img pairs in a sequence to train the model?

**Comment by noahzn** [comment]
It uses adjacent frames to compute the loss, but the prediction is on a single frame.

**Comment by renyuanzhe** [comment]
so the gt of the input img is the adjacent frame of the input img ?

**Comment by noahzn** [comment]
No. You can read the paper or the source code to get a quick idea of how self-supervised depth estimation works.
