### ISSUE TITLE
About the test evaluation on Make3D dataset

### ISSUE THREAD

**Issue by MrBelly** [noahzn/Lite-Mono#128]
Dear Author,

I hope you are having a good day. and thank you for your work.  I am trying to reproduce the results of make 3D dataset but the values are slightly different from the values proposed in the paper,  I would be happy, if you help me with this.  Thanks in advance.

my results
abs_rel        sq_rel      rmse          rmse_log
0,312           3.278       7.136         0,161     

[script.txt](https://github.com/noahzn/Lite-Mono/files/14683669/script.txt)

**Comment by noahzn** [comment]
Hi, please take a look at this [link](https://github.com/nianticlabs/monodepth2/issues/392).

**Comment by MrBelly** [comment]
Hi, thanks for your reply.  I have already manipulated the code from the link.  It gives similar results in monodepth2 but I could not get similar results for lite-mono.

**Comment by noahzn** [comment]
Please make sure if you are using the correct lite-mono checkpoint. What results did you get after modifying your code?

**Comment by MrBelly** [comment]
Ok I found out my error thanks for your time and reply
