### ISSUE TITLE
tensorboard file

### ISSUE THREAD

**Issue by DongyangHuLi** [noahzn/Lite-Mono#13]
Hi~, can you provide training logs on kitti dataset? For example, the tensorboard file, I want to make a comparison with my training process.

**Comment by noahzn** [comment]
Hi, I don't keep the log files.

**Comment by noahzn** [comment]
One tip, please set `--mypretrain` if you want to load the ImageNet pre-trained weights.

**Comment by noahzn** [comment]
Closed due to no response.
