### ISSUE TITLE
How the reproduction of the results of the model achieves the results in the paper

### ISSUE THREAD

**Issue by LLLYLong** [noahzn/Lite-Mono#130]
Many thanks to the author for such a great article.

I trained Lite-mono with the parameters you gave me, but the results I got were quite different from the article, with gaps in every metric. Is there any special settings to reproduce the best results?
Secondly, can you help me to see if the training process is correct and if the losses and the metrics are in order.
My training parameters are as follows: batch_size is set to 24, png images are used, and no other changes are made.

I'm looking forward to hearing from you.
复现结果
   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.109  &   0.821  &   4.657  &   0.186  &   0.884  &   0.961  &   0.982  \\
  flops: 5.032G, params: 3.069M, flops_e: 4.314G, params_e:2.842M, flops_d:718.295M, params_d:226.627K

![Snipaste_2024-03-28_14-39-12](https://github.com/noahzn/Lite-Mono/assets/100742254/8741086d-2389-4354-afb6-fc2bd5e4d22c)

**Comment by noahzn** [comment]
Hi, the difference in results is too much.
Please strictly follow the dependencies we used for training. Also, we used `.jpg`.

Here are some useful links you can take a look. 
https://github.com/noahzn/Lite-Mono/issues/7
https://github.com/noahzn/Lite-Mono/issues/4
https://github.com/noahzn/Lite-Mono/issues/58

**Comment by noahzn** [comment]
I am now closing this thread due to lack of response. You can reopen it or create a new issue if you have further questions.
