### ISSUE TITLE
Inexplicable "No such file or directory: 'Lite-Mono-main\\kitti_data\\\2011_09_26/2011_09_26_drive_0002_sync\\\image_02/data\\- 000000001.png'"

### ISSUE THREAD

**Issue by own295554312** [noahzn/Lite-Mono#135]
When I train the model, I get this error. My confusion is:
1, my training splits do not have the
2011_09_26_drive_0002_sync\\\\image_02/data\\\- 000000001.png. I am not sure why this path is indexed.
2. there is a file under this path, I'm not sure why I can't find the file under this path
<img width="807" alt="微信图片_20240410125243" src="https://github.com/noahzn/Lite-Mono/assets/134125011/74ab534a-d74b-4f8c-ae92-5d012c0d4df6">

**Comment by noahzn** [comment]
Hi, why is there a hyphen (-) at the beginning of the file name? Did you change the data loader?

**Comment by noahzn** [comment]
I'm now closing this issue as there is no response.

**Comment by Edric-star** [comment]
> I'm now closing this issue as there is no response.

His problem was the same as mine... But unluckily he didn't seem to focus on it anymore.
