### ISSUE TITLE
the CPU utilization has been very high, but the GPU utilization has been very low

### ISSUE THREAD

**Issue by lshhan** [noahzn/Lite-Mono#136]
Hello, I would like to ask if the data loading part of the code is performed on the CPU? During my experiment, the CPU utilization has been very high, but the GPU utilization has been very low. What is the reason for this?
![cpu](https://github.com/noahzn/Lite-Mono/assets/166673031/2bf42957-7115-48a4-baa9-689f2361914e)
![image](https://github.com/noahzn/Lite-Mono/assets/166673031/f10802b7-8a47-48e2-bdbc-722a8c82d9b3)

**Comment by noahzn** [comment]
Hi, yes, the data loading is performed on CPUs. Then, they are moved to GPUs (https://github.com/noahzn/Lite-Mono/blob/main/trainer.py#L269)

**Comment by noahzn** [comment]
I'm now closing this issue as there is no response.
