### ISSUE TITLE
About indicator sq_rel

### ISSUE THREAD

**Issue by LLLYLong** [noahzn/Lite-Mono#138]
Hello author, I am lucky to see such an excellent article.
I would like to ask a question, what is the reason that when retraining, all other metrics are performing well and sq_rel has been difficult to lower. This problem has puzzled me for a long time and I have not been able to find a good method, I would like to ask the author if he has also encountered this kind of problem and how should I go about solving it. I am looking forward to the author's reply, thank you.
my train
![image](https://github.com/noahzn/Lite-Mono/assets/100742254/18e22f98-bcd7-4c56-abb9-73c15f5d7668)

paper
![image](https://github.com/noahzn/Lite-Mono/assets/100742254/01e12d53-c33b-4fa3-b593-16f7d0157fdd)

I would also like to say that this problem is also not specific to that network, but is a problem I encountered while making further modifications, and would like to ask the authors for their experience if they have encountered a similar one during their experiments

**Comment by noahzn** [comment]
Hi, it's good to know that you have improved the results a lot since last time you asked me.

`sq_rel` is square relative error (`|d_pred - d_gt| ^2 / d_gt`). I think this error may be reduced if you have smoother and more consistent depth predictions.

**Comment by noahzn** [comment]
I am now closing this issue as there is no feedback.

**Comment by LLLYLong** [comment]
Thanks for the author's reply, I apologize for not seeing the message in time, I'll try the smoothing factor right away to see if it makes a difference

**Comment by LLLYLong** [comment]
> I am now closing this issue as there is no feedback.

Thanks for the author's reply, I apologize for not seeing the message in time, I'll try the smoothing factor right away to see if it makes a difference.

I would also like to ask a question, does the author know anything about the relationship between relative depth and metric depth, I'm a bit confused now, how is the relative depth converted to metric depth, do they just differ by an unknown focal length?

**Comment by noahzn** [comment]
@LLLYLong Just like other monocular self-supervised method, Lite-Mono can only predict relative depth. But in the evaluation we use median filter to scale the depth values.

**Comment by LLLYLong** [comment]
> @LLLYLong Just like other monocular self-supervised method, Lite-Mono can only predict relative depth. But in the evaluation we use median filter to scale the depth values.

@noahzn Scaling depth using median filtering also makes the depth value meaningful. 
Am I to understand that there is a scaling factor difference between the relative depth and the metric depth. 
That is, the network predicts relative depth, and if I specify a range of depths and scale the depth map, I get metric depth.

**Comment by noahzn** [comment]
But in this way you cannot get very accurate depth. It also depends on the dataset you use.
