### ISSUE TITLE
Test outputs is black

### ISSUE THREAD

**Issue by VictorWylde** [noahzn/Lite-Mono#139]
Hello, I imitated KITTIOdomDataset to read my own video frames, but the output images of **test_simple.py** are all black or yellow. What is the problem? I train the following pretrained models and get the results:

- black: lite-mono-8m_1024_320-resnet50-separate_resnet，lite-mono-8m_640_192-resnet50-separate_resnet
- yellow: lite-mono-8m_1024_320-resnet18-separate_resnet
- normal: lite-mono-8m_640_192-resnet18-separate_resnet

**Comment by noahzn** [comment]
Hi, can you show some images? Are they shown correctly during training in the tensorboard?

**Comment by VictorWylde** [comment]
Sorry for the late reply. I would like to upload the training results, but there have been issues with GitHub's push.
This is the opt.json for the inference results and training weights.

![covered_complete_covered_elevator_0](https://github.com/noahzn/Lite-Mono/assets/98001917/cbd12332-d065-413d-9273-d8d2f73d9c03)
![covered_complete_covered_elevator_0_disp](https://github.com/noahzn/Lite-Mono/assets/98001917/a68b289d-3329-46ce-bd97-312659bc5489)

**Comment by VictorWylde** [comment]
```json
{
  "data_path": "/workspace/IPC_Indoor_20231030_1530_P",
  "log_dir": "/mnt/smb-149/02_Tasks/01_Depth_Estimation/Lite-Mono-main/tmp",
  "model_name": "mytrain-010-lite-mono-8m_640_192-resnet50-separate_resnet",
  "split": "odom",
  "split_num": 3,
  "model": "lite-mono-8m",
  "weight_decay": 0.01,
  "drop_path": 0.2,
  "num_layers": 50,
  "dataset": "lift_odom",
  "png": false,
  "height": 192,
  "width": 640,
  "disparity_smoothness": 0.001,
  "scales": [
    0,
    1,
    2
  ],
  "min_depth": 0.1,
  "max_depth": 100.0,
  "use_stereo": false,
  "frame_ids": [
    0,
    -1,
    1
  ],
  "profile": true,
  "batch_size": 12,
  "lr": [
    0.001,
    5e-06,
    31.0,
    0.001,
    5e-06,
    31.0
  ],
  "num_epochs": 30,
  "scheduler_step_size": 30,
  "v1_multiscale": false,
  "avg_reprojection": false,
  "disable_automasking": false,
  "predictive_mask": false,
  "no_ssim": false,
  "mypretrain": null,
  "weights_init": "pretrained",
  "pose_model_input": "pairs",
  "pose_model_type": "separate_resnet",
  "no_cuda": false,
  "num_workers": 12,
  "load_weights_folder": "pretrain_weights/lite-mono-8m_640_192/",
  "models_to_load": [
    "encoder",
    "depth"
  ],
  "log_frequency": 10,
  "save_frequency": 3,
  "disable_median_scaling": false,
  "pred_depth_scale_factor": 1,
  "ext_disp_to_eval": null,
  "eval_split": "eigen",
  "save_pred_disps": false,
  "no_eval": false,
  "eval_out_dir": null,
  "post_process": false
}
```

**Comment by noahzn** [comment]
Since the depth range of your image is small, so you need to change `max_depth` in the configuration. The most important thing is to change the camera intrinsics in the dataset class.

**Comment by VictorWylde** [comment]
Thank you for your help!! And I have other questions:

(1) What is the unit of this parameter `max_depth`, centimeters or meters?

(2) How can I obtain `KITTIDataset(). K` from the camera?

**Comment by noahzn** [comment]
1) meter
2) If you collect your dataset using your own camera, then you need to calibrate your camera. There are a lot of documentations on camera calibration.

**Comment by VictorWylde** [comment]
Okay, thank you very much! I'll train it again.

**Comment by noahzn** [comment]
I am now closing this issue as there is no further update.
