### ISSUE TITLE
evaluation error [ValueError: too many values to unpack (expected 2)]

### ISSUE THREAD

**Issue by Jacksonfei** [noahzn/Lite-Mono#14]
dear author:

when i run your eval command in a conda env:

$ python evaluate_depth.py --load_weights_folder xxx/lite-mono/weights/input_size_1024_320/lite-mono_1024x320 --data_path xxx/kitti_depth_data --model lite-mono

the outputs from the terminal:
```
Traceback (most recent call last):
  File "evaluate_depth.py", line 223, in <module>
    evaluate(options.parse())
  File "evaluate_depth.py", line 131, in evaluate
    output, _ = depth_decoder(encoder(input_color))
ValueError: too many values to unpack (expected 2)
```

how can i slove this problem? thanks a lot!

**Comment by noahzn** [comment]
Hi @Jacksonfei , it should work now. Could you try again?

**Comment by Jacksonfei** [comment]
Thanks for your fast response, it works now! 
In addition,  when I run the test_simple.py,  the data in the generated .npy file is the absolute depth of  each pixel on the raw image, and the unit is meter, right?
Some data in npy file like that :[[[[1.7596681 1.7489609 1.7277021 ... 1.8009529 1.8252897 1.8375546] .....

**Comment by Jacksonfei** [comment]
i see, thanks a lot!

**Comment by Jacksonfei** [comment]
BTW, can you give some suggestions to easily obtain the absolute depth of each pixel using momo method?

**Comment by noahzn** [comment]
If you are training on your own dataset you can use some depth sensors to check the absolute depth of some pixels and then get an estimated scale factor. For the KITTI dataset you can try similar things but using the ground truth of depth.

**Comment by Jacksonfei** [comment]
Thanks for your advice, i will try it soon~

**Comment by noahzn** [comment]
You are welcome. Please close this issue if it is solved.
