### ISSUE TITLE
Subsequent issues with gt_depths.npz

### ISSUE THREAD

**Issue by 11123jiang** [noahzn/Lite-Mono#149]
Hello, I encountered the following error while evaluating gt_depths.npz generated using export_gt_depth.py:
Traceback (most recent call last):
File "evaluate_depth.py",  line 226, in <module>
evaluate(options.parse())
File "evaluate_depth.py",  line 169, in evaluate
gt_depths = np.load(gt_path, fix_imports=True, encoding='latin1', allow_pickle=True)["data"]
File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py",  line 260, in __getitem__
raise KeyError("%s is not a file in the archive" % key)
KeyError: 'data is not a file in the archive'
Afterwards, the content of npz printed out includes some numbers ['69 ','54','42 ','57','30 ','27','12 ','75','36 ','33','15 ','72','3 ','39']
What should I do next to conduct an evaluation

**Comment by noahzn** [comment]
Hi, it seems your ground-truth file is corrupted. Could you try generating gt_depths.npz again?

**Comment by 11123jiang** [comment]
I tried generating again, but still encountered this problem. Can you send gt_depths.npz to my email jas111@stud.tjut.edu.cn

**Comment by noahzn** [comment]
Hi, currently I don't have this file in my laptop. I just googled this file, could you try downloading from this [link](https://github.com/nianticlabs/depth-hints/blob/master/splits/eigen/gt_depths.npz)?

**Comment by 11123jiang** [comment]
OK, thank you very much for your help
