### ISSUE TITLE
sorry to bothering you

### ISSUE THREAD

**Issue by QingTianNNN** [noahzn/Lite-Mono#150]
I apologize for bothering you. Could you explain what ‘local information’ and ‘global information’ mean in the context of local-global feature interaction?

**Comment by noahzn** [comment]
Hi, using CNNs to extract features have limited receptive fields and the information focuses on local regions to learn edges, textures, etc. The LGFI module allows models to understand both fine details and overall context. Vision transformers are used to extract global information on the feature maps.
