### ISSUE TITLE
Output resolution problem

### ISSUE THREAD

**Issue by swing2331** [noahzn/Lite-Mono#151]
Hi
I tried to train with a custom dataset of 640*480 and tested it on the .pth I got using test_simple.py. Why is the resulting .npy depth map size 640*192 instead of the 640*480 I set?

**Comment by swing2331** [comment]
My data set is aerial images taken by drones, and the test results are as follows:
Original image，![0000001544](https://github.com/user-attachments/assets/26cddb88-cf83-4220-95f4-2ccdbf9c465c)
Depth Map，![0000001544_disp](https://github.com/user-attachments/assets/ede54efe-2599-482d-9f28-6a831a5d968e)
.npy Depth Map，![sd1](https://github.com/user-attachments/assets/cc97244f-3d19-4e21-90a5-01b848060933)

**Comment by noahzn** [comment]
Hi, in the [options](https://github.com/noahzn/Lite-Mono/blob/main/options.py#L59) you can change the width and height. Did you change the camera intrinsics before training the network?

**Comment by swing2331** [comment]
Yes, I changed the size in the opening, but the. npy size output by test_Simple.py is still 640 * 192

**Comment by noahzn** [comment]
Can you validate that the size you used for training is correct? Because the image size is read from the trained model, see the code [here](https://github.com/noahzn/Lite-Mono/blob/main/test_simple.py#L77). I guess you trained your model using `640*192`

**Comment by swing2331** [comment]
Yes, upon inspection, it was found that I used a size of 192 * 640 for training. I will retrain. Thank you for your answer!
