### ISSUE TITLE
How to set proper dilation values?

### ISSUE THREAD

**Issue by yyyxs1125** [noahzn/Lite-Mono#155]
Hi!
If I want to train on my dataset and the resolution is 1920 x 1200, how to set proper dilation values for lite-mono:
`if model == 'lite-mono':
            self.num_ch_enc = np.array([48, 80, 128])
            self.depth = [4, 4, 10]
            self.dims = [48, 80, 128]
            if height == 192 and width == 640:
                self.dilation = [[1, 2, 3], [1, 2, 3], [1, 2, 3, 1, 2, 3, 2, 4, 6]]
            elif height == 320 and width == 1024:
                self.dilation = [[1, 2, 5], [1, 2, 5], [1, 2, 5, 1, 2, 5, 2, 4, 10]]`
And I also found that width and height must can be devided by 32, if I resize all images to 1920 x 1184, what else should also be modified? Thanks.

**Comment by noahzn** [comment]
Hi, you can start from the default dilation rates when height is 192 and width is 640. It's very important to change the intrinsics. https://github.com/noahzn/Lite-Mono/blob/main/datasets/kitti_dataset.py#L18

**Comment by yyyxs1125** [comment]
Thank you for the quick reply, if I change image shape to 1920 x 1184, does the intrinsic matrix need a change?

**Comment by noahzn** [comment]
Is your dataset a custom one?

**Comment by yyyxs1125** [comment]
Yes, it is.

**Comment by noahzn** [comment]
Then you need to calibrate your camera and get the `K`

**Comment by yyyxs1125** [comment]
I already get the K for from camera, my question is whether the original intrinsic matrix still applies when the image size has changed.

**Comment by noahzn** [comment]
yes

**Comment by yyyxs1125** [comment]
Thank you so much.
