### ISSUE TITLE
ImageNet Pretrained 1024X320

### ISSUE THREAD

**Issue by sundayzl66** [noahzn/Lite-Mono#156]
hi, dear noahzn, I am so excited about your outstanding work that I wanna exploring more. Do you have the plan to release the pretrained models whose input-size is 1024*320?
Looking forward to your reply, thanks~

**Comment by noahzn** [comment]
Hi @sundayzl66, the pretrained models are resolution agnostic. For the same network structure (lite-mono, small, tiny, 8m) , we used the same pretrained model for different resolutions.

**Comment by sundayzl66** [comment]
Do you mean that when training lite-mono at 1024x320 and 640x192, the same ImageNet Pretrained model of 640x192 is used?

**Comment by noahzn** [comment]
Yes.

**Comment by sundayzl66** [comment]
Thank you very much! So, do I only need the following parts for training?

def __init__(self, in_chans=3, model='lite-mono', height=320, width=1024,
                 global_block=[1, 1, 1], global_block_type=['LGFI', 'LGFI', 'LGFI'],
                 drop_path_rate=0.2, layer_scale_init_value=1e-6, expan_ratio=6,
                 heads=[8, 8, 8], use_pos_embd_xca=[True, False, False], **kwargs):

**Comment by noahzn** [comment]
yes, you only need to change `height` and `width`.

**Comment by sundayzl66** [comment]
Do I need to modify anything during evaluation?

**Comment by noahzn** [comment]
As the width and height information is recorded in the checkpoint, it should be ok not to modify anything for the evaluation.

**Comment by sundayzl66** [comment]
Okay, thank you very much! You can close this issue now.
