### ISSUE TITLE
training

### ISSUE THREAD

**Issue by sundayzl66** [noahzn/Lite-Mono#157]
hi, dear noahzn，after training Lite-Mono with a resolution of 320x1024, I started the evaluation, but why is it still displaying 192x640?
![image](https://github.com/user-attachments/assets/a3b3b5c5-0c22-4bbc-a09d-fa34cb4953b9)

**Comment by noahzn** [comment]
Hi @sundayzl66, how did you modify the code? Did you also modify the `width` and `height` in this [file](https://github.com/noahzn/Lite-Mono/blob/main/options.py)?

**Comment by sundayzl66** [comment]
Sorry, I haven't modified this file.

**Comment by sundayzl66** [comment]
self.parser.add_argument("--height",
                                 type=int,
                                 help="input image height",
                                 default=320)
        self.parser.add_argument("--width",
                                 type=int,
                                 help="input image width",
                                 default=1024)
Is that all right

**Comment by noahzn** [comment]
> ```
>     self.parser.add_argument("--height",
>                              type=int,
>                              help="input image height",
>                              default=320)
>     self.parser.add_argument("--width",
>                              type=int,
>                              help="input image width",
>                              default=1024)
> ```
> 
> Is that all right

Yes.

**Comment by sundayzl66** [comment]
Okay, thank you.
