### ISSUE TITLE
ImageNet pretrained weights

### ISSUE THREAD

**Issue by lonelysheeep** [noahzn/Lite-Mono#16]
I use your source code to reproduce the paper, the result is worse, where <1.25 is only 0.852, is there something wrong with the source code?

**Comment by noahzn** [comment]
Hi, <1.25=0.852 is abnormal. What PyTorch version do you use? The source code should work without problems. As far as I know, at least 5 people have reproduced the results.

**Comment by lonelysheeep** [comment]
1.7.1，I found that the splits in your code are incomplete, I used the splits in mono2 instead of yours, does this matter?

**Comment by noahzn** [comment]
Yes. This repo only contains the Eigen test files. You need to prepare the `train_files.txt` and `val_files.txt`

**Comment by lonelysheeep** [comment]
So may I ask, if I want to reproduce the code to achieve your effect, what else do I need to do besides downloading the code from github and running it according to the readme instructions? For example in the other question it was mentioned that I need to download the pre-trained model or something else?

**Comment by noahzn** [comment]
Yes, if you want to use the ImageNet pre-trained weights you need to download the pre-trained model and load it by setting `--mypretrain`

**Comment by lonelysheeep** [comment]
Thank you for your answer, I will try again

**Comment by lonelysheeep** [comment]
Can you provide me with the download path for the ImageNet pre-training model? I've downloaded several but they don't seem to work

**Comment by noahzn** [comment]
You can find all the download links you need in the `README.md` file.

**Comment by lonelysheeep** [comment]
thanks
