### ISSUE TITLE
train

### ISSUE THREAD

**Issue by swing2331** [noahzn/Lite-Mono#161]
Hi，
Can I train a lite-mono model using consecutive frames from several different videos?

**Comment by noahzn** [comment]
Hi @swing2331, what do you mean "several different videos"? Were those videos taken by the same camera? Do you know the intrinsic of the camera?

**Comment by swing2331** [comment]
The videos are from the same camera with known intrinsics, but taken at different times

**Comment by noahzn** [comment]
I see. You can use the videos for training.
In this paper I collected videos from different scenes and use them for training Lite-Mono.
https://www.mdpi.com/2504-446X/8/2/33

**Comment by swing2331** [comment]
I understand. Thanks！
