### ISSUE TITLE
The results of the assessment were not good

### ISSUE THREAD

**Issue by STCQWE** [noahzn/Lite-Mono#162]
Thanks for the wonderful works!! It helps me a lot!
After 30 rounds of training with your script, I found that the results of the assessment were not very good, as shown below
![结果1](https://github.com/user-attachments/assets/5b6d293c-57f3-4ad3-859a-c15cfabf6427)

What could be the problem and would like to seek some help
Looking forward to your reply, thank you!

**Comment by noahzn** [comment]
Hi, can you try PyTorch 1.7.1 or 1.12.1?

**Comment by noahzn** [comment]
I am now closing this issue as there is no response.
