### ISSUE TITLE
Training issues on the Cityscapes dataset

### ISSUE THREAD

**Issue by zhangtian33** [noahzn/Lite-Mono#163]
First of all, thank you for your excellent work.
When I trained using LiteMono on the Cityscapes dataset, I found that its performance on this model was not very satisfactory. Do you have any related training results? I am not yet sure if it is an issue with code modifications or with the model itself. I have uploaded the results on the Cityscapes dataset below: 
![1731301968115](https://github.com/user-attachments/assets/9b004026-3935-468d-9eaa-39f1c764bf23)

**Comment by noahzn** [comment]
Hi, what PyTorch version did you use for training?

**Comment by zhangtian33** [comment]
I'm using PyTorch version 2.3.0 with CUDA version cu121. My model's performance on the KITTI dataset is:
![Uploading 1731302368050.jpg…]()

**Comment by zhangtian33** [comment]
I'm using PyTorch version 2.3.0 with CUDA version cu121. My model's performance on the KITTI dataset is:
![1731302368050](https://github.com/user-attachments/assets/15f3e7c6-2b03-4b25-98bb-5a2d48346e36)

**Comment by zhangtian33** [comment]
> Hi, what PyTorch version did you use for training?

I believe that the results I obtained from training on the KITTI dataset are normal.

**Comment by noahzn** [comment]
Many users have reported poor training results when they use the newer versions. Can you try PyTorch 1.7.1 or 1.12.1? But, your training on KITTI is normal.

**Comment by zhangtian33** [comment]
> Many users have reported poor training results when they use the newer versions. Can you try PyTorch 1.7.1 or 1.12.1? But, your training on KITTI is normal.

Thank you for your reply. I will try using the dependencies you provided. Additionally, I would like to know if you have trained on the Cityscapes dataset, and how the performance was?

**Comment by noahzn** [comment]
No. I didn't train on Cityscapes.

**Comment by zhangtian33** [comment]
> No. I didn't train on Cityscapes.

Thank you again for your response. I found some discrepancies between my evaluation code and the existing evaluation method. After making adjustments, the optimal results obtained are as follows:
![1731327397172](https://github.com/user-attachments/assets/1468e348-e7e5-484f-87e3-004c7c88e9a6)

**Comment by noahzn** [comment]
I see. This seems better!
