### ISSUE TITLE
Model Testing

### ISSUE THREAD

**Issue by swing2331** [noahzn/Lite-Mono#164]
Hi，
The testing and evaluation codes test_Simple.py and evaluate_depth.py for the model seem to only call DepthNet. How can PoseNet be evaluated or tested？

**Comment by noahzn** [comment]
Hi, in this paper we didn't evaluate PoseNet.

**Comment by swing2331** [comment]
So PoseNet is only used for training models？

**Comment by noahzn** [comment]
Yes, this is the case.

**Comment by swing2331** [comment]
Thank you for your reply！
