### ISSUE TITLE
 inputs[key] = ipt.to(self.device)，AttributeError: 'NoneType' object has no attribute 'to'`

### ISSUE THREAD

**Issue by AZong76** [noahzn/Lite-Mono#22]
Hello, we attempted to run Lite mono's training, and we prepared the kitti dataset and successfully loaded it. However, while training, we encountered the following problem:

`(dh_robodepth) lyu4@lyu4:~/dh_wp/Lite-Mono-main$ CUDA_VISIBLE_DEVICES=1 python train.py
Training model named:
   mymono
Models and tensorboard events files are saved to:
   ./tmp
Training is using:
   cuda
/home/lyu4/anaconda3/envs/dh_robodepth/lib/python3.10/site-packages/torchvision/transforms/transforms.py:332: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
Using split:
   eigen_zhou
There are 39810 training items and 4424 validation items

Training
Traceback (most recent call last):
  File "/home/lyu4/dh_wp/Lite-Mono-main/train.py", line 12, in <module>
    trainer.train()
  File "/home/lyu4/dh_wp/Lite-Mono-main/trainer.py", line 218, in train
    self.run_epoch()
  File "/home/lyu4/dh_wp/Lite-Mono-main/trainer.py", line 237, in run_epoch
    outputs, losses = self.process_batch(inputs)
  File "/home/lyu4/dh_wp/Lite-Mono-main/trainer.py", line 268, in process_batch
    inputs[key] = ipt.to(self.device)
AttributeError: 'NoneType' object has no attribute 'to'`

We have tried many methods, but have been stuck here. Can you help me solve this problem? thank

**Comment by noahzn** [comment]
Hi, it seems that the code didn't load your data successfully. Could you try to check if [here](https://github.com/noahzn/Lite-Mono/blob/main/trainer.py#L237) the `inputs` is `None`?

**Comment by AZong76** [comment]
Thank you, we have solved this problem
