### ISSUE TITLE
The questions about the ImageNet pre-trained model

### ISSUE THREAD

**Issue by ZC0015wqj** [noahzn/Lite-Mono#24]
Hello, I would like to ask if the ImageNet pre-training model is obtained by training with the current network model using the ImageNet dataset, and then load this pre-training model when training on the kitti dataset, right?

**Comment by noahzn** [comment]
Hi, yes. The encoder of the DepthNet was trained as a classification model using the ImageNet dataset. Then, the weights are loaded by setting `--mypretrain`.

**Comment by ZC0015wqj** [comment]
After I changed the network, there was a problem that the Image Net pre-training model could not be loaded. Can I put the modified model on the Image Net dataset for training, and then use the trained model file as a pre-training model in Kitti_data training on the dataset

**Comment by noahzn** [comment]
Hi, if you have changed a small part of the network you can still load most of the pre-trained weights, but you will need to modify the code a little to make it only load certain weights. You can check out this [function](https://github.com/noahzn/Lite-Mono/blob/main/trainer.py#L655) that we currently use to load a pre-trained model. It removes the last norm layer of the pre-trained model. 

If you have made major changes to the model and want to create your own pre-trained model, you can train it on ImageNet and then use it as a pre-trained model and fine-tune it on KITTI.

**Comment by ZC0015wqj** [comment]
```python
RuntimeError: Error(s) in loading state_dict for LiteMono:
	size mismatch for stages.0.3.pwconv2.weight: copying a param with shape torch.Size([48, 288]) from checkpoint, the shape in current model is torch.Size([288, 288]).
	size mismatch for stages.0.3.pwconv2.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([288]).
	size mismatch for stages.1.3.pwconv2.weight: copying a param with shape torch.Size([80, 480]) from checkpoint, the shape in current model is torch.Size([480, 480]).
	size mismatch for stages.1.3.pwconv2.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([480]).
	size mismatch for stages.2.9.pwconv2.weight: copying a param with shape torch.Size([128, 768]) from checkpoint, the shape in current model is torch.Size([768, 768]).
	size mismatch for stages.2.9.pwconv2.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([768])
``` 
It seems that this can’t be solved by loading some weights. Can you tell me which year’s data is the data set you use? Can you provide a download link? If possible, I’m really grateful

**Comment by ZC0015wqj** [comment]
Sorry, I didn't make it clear. I know this is due to the problem of pre-training weight loading. What I want to ask is what version of the ImageNet dataset is, because I saw different data from different years on the official website

**Comment by noahzn** [comment]
Hi, the version of ImageNet is 2012 (ILSVRC2012)
