### ISSUE TITLE
Can it be used for face depth estimation?

### ISSUE THREAD

**Issue by chen990627** [noahzn/Lite-Mono#25]

**Comment by noahzn** [comment]
Hi, I don't think the method can be **directly** used for face depth estimation. The self-supervised method is based on camera motions and uses adjacent frames for image reconstruction. But of course, you can use the pre-trained Lite-Mono backbones to design a supervised method. The model itself is lightweight and can be used as a base model for a variety of tasks.

**Comment by noahzn** [comment]
I'm closing this issue due to no response. Please reopen it if you have any further comments.
