### ISSUE TITLE
Evaluation File not Found: gt_depth.npz

### ISSUE THREAD

**Issue by justbuyyal** [noahzn/Lite-Mono#26]
According to evaluation step, I want to evaluate KITTI Eigen Dataset, but I had encountered a lost of file error. Is there any link to download the `gt_depth.npz` file ?

**Comment by noahzn** [comment]
Hi! You can download the file `export_gt_depth.py` from [Monodepth2](https://github.com/nianticlabs/monodepth2), and then run `python export_gt_depth.py --data_path kitti_data --split eigen` to prepare the ground-truth. More information regarding the data preparation can be also found on their repo.

**Comment by justbuyyal** [comment]
OK, it fixed, thanks for help !
