### ISSUE TITLE
'LiteMono' object has no attribute 'dilation'

### ISSUE THREAD

**Issue by jiangxf0929** [noahzn/Lite-Mono#27]
Hi, when I train my dataset and load weights to test, I get the following error, what is the reason?
AttributeError: 'LiteMono' object has no attribute 'dilation'

**Comment by noahzn** [comment]
Hi, which file did you run? Can you copy the complete error message?

**Comment by jiangxf0929** [comment]
hello, My test command is "python test_simple.py --load_weights_folder ./tmp/Mytrain/  --image_path ./data/mydata/image_02/data/", train command is "python train.py --data_path ./data --model_name mytrain --num_epochs 30 --batch_size 2 --mypretrain ./preweights/lite-mono-pretrain.pth --lr 0.0001 5e-6 31 0.0001 1e-5 31". Error message is "-> Loading model from  ./tmp/Mytrain/
   Loading pretrained encoder
Traceback (most recent call last):
  File "test_simple.py", line 192, in <module>
    test_simple(args)
  File "test_simple.py", line 81, in test_simple
    encoder = networks.LiteMono(model=args.model,
  File "/Lite-Mono-main/networks/depth_encoder.py", line 384, in __init__
    stage_blocks.append(DilatedConv(dim=self.dims[i], k=3, dilation=self.dilation[i][j], drop_path=dp_rates[cur + j],
  File "/miniconda3/envs/nerf-pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LiteMono' object has no attribute 'dilation'"

**Comment by noahzn** [comment]
What version of PyTorch are you using? There seems to be a problem on the PyTorch side.

**Comment by jiangxf0929** [comment]
torch 1.12.1, Which version did you use in LiteMono?

**Comment by noahzn** [comment]
I tested with PyTorch `1.7.1` and `1.12.1`. 
Could you check if you are using the correct checkpoints? For testing you need to load this [checkpoint (default: Lite-Mono)](https://surfdrive.surf.nl/files/index.php/s/IK3VtPj6b5FkVnl) by setting `--load_weights_folder`, and for training  please load [this file](https://surfdrive.surf.nl/files/index.php/s/InMMGd5ZP2fXuia) by setting `--mypretrain`

**Comment by jiangxf0929** [comment]
I have tested with your checkpoint (lite-mono_1024 and lite-mono_640), and it works. but when I use your pretrain.pth to train and test my data, the same error appears.

**Comment by jiangxf0929** [comment]
Ok, I find, my image size is not 640*192 or 1024*320

**Comment by noahzn** [comment]
Glad you found the problem! If you want to train with different image sizes, you can modify the code.

**Comment by jiangxf0929** [comment]
Many thanks for your patience and help! 😊
