### ISSUE TITLE
Training the model via Google Colab using cloud storage

### ISSUE THREAD

**Issue by Ark3M** [noahzn/Lite-Mono#28]
Hi! I'd like to train your model (for example, a lite-mono with 3.1M params) using Google Colab. I found out that the uploading speed is quite slow if I try to upload all the data directly to Colab. So, because of that I've decided to try using some cloud storage. Specifically, I have a bucket in Yandex Object Storage with the entire KITTI data.
Please, can you give me advice how I should access all this data properly during my training process? Is it possible, at least? In other words, I'd like to access the data as needed during the training - so I won't have to store the entire dataset on my Colab machine.

**Comment by noahzn** [comment]
Hi! I didn't know Yandex Object Storage. Does it provide the interface from which Colab can read data? If uploading directly to Colab is slow, you may want to try uploading to Google Drive first, and then access Google Drive from Google Colab.

**Comment by Ark3M** [comment]
@noahzn Thank you for your response! Yeah, I think I should stick to the case, in which I upload the data to Google Drive first, and then access it from Google Colab. From my point of view, it's much more intuitive way to solve this issue, than try to use Yandex Object Storage bucket. As I understood, Yandex hasn't provided any user-friendly interface to access the data from Google Colab. I'll try to train the model in the way mentioned at the beginning of this passage, and after that I'll let you know!

**Comment by Byronnar** [comment]
Hi, Where is the linear_warmup_cosine_annealing_warm_restarts_weight_decay file? I got the error:ModuleNotFoundError: No module named 'linear_warmup_cosine_annealing_warm_restarts_weight_decay'  @noahzn
