### ISSUE TITLE
Can you share the code for calculating FLOPs?

### ISSUE THREAD

**Issue by whyygug** [noahzn/Lite-Mono#29]
Thank you for the wonderful work!

I would like to know how you calculate the FlOPs? What libraries do you use?
I have tried using FVCORE to calculate FLOPs, but that library does not seem to support GELU. 
In addition, many libraries do not support models with lists in the input, so they cannot calculate FLOPs for the depth decoder.
Can you share the code for calculating FLOPs? Many thanks!

**Comment by noahzn** [comment]
Hi, thank you for your interest in our work!

[This function](https://github.com/noahzn/Lite-Mono/blob/main/evaluate_depth.py#L22) calculates the parameters and FLOPs. The library is `thop`.

**Comment by whyygug** [comment]
Thank you very much for your quick reply!
