### ISSUE TITLE
About no imagenet pre-train

### ISSUE THREAD

**Issue by 413090531** [noahzn/Lite-Mono#30]
Thank you again for answering my question in such detail before! I am coming again.

I noticed that there are no imagenet pre-training results in the article. I found that both the depth encoder and the pose encoder in the code inherit the weight of imagenet.I want to know how the results without imagenet pre-training in the article are obtained. Only the depth network without pre-training or the pose network and the deep network without pre-training at the same time?

Looking forward to your reply.

**Comment by noahzn** [comment]
Hi @413090531!
For the DepthNet only the `depth_encoder` load the pre-trained weights. depth_decoder's weights are initialized, but they are not pre-trained weights. 
If you do not want to use the ImageNet pre-training you can simply **not** set `--mypretrain`. Then, both the encoder and decoder are [initialized](https://github.com/noahzn/Lite-Mono/blob/main/networks/depth_encoder.py#L393). But the PoseNet still loads the pre-trained weights, which is a default setting.

**Comment by 413090531** [comment]
Thank you for your reply, I understand how to set the parameters, I will try to run the code.

**Comment by 413090531** [comment]
Hello @noahzn! It's so nice of you! You really helped me a lot! I want to use the ImageNet pre-training model of lite-mono params=3.1M 1024x320 for experiments, I mean the model after ImageNet pre-training, not after depth estimation training. But I found that the pre-training model has not been published, I would like to know if it is convenient for you to publish the pre-training model or send this pre-training model to me, my email is shanwc97@gmail.com.Thank you very much!

Looking forward to your reply.

**Comment by noahzn** [comment]
Hi, I didn't make a different pre-training, so the pre-trained model is the same for the same architecture with different input sizes. You can use the pre-trained weights for Lite-Mono-640x192

**Comment by 413090531** [comment]
Thanks for your reply, I will try to use the pre-trained model of Lite-Mono-640x192. By the way, if I want to run the resolution of 1024x320, do I need to change other parameters besides the height and width in the options.py?

**Comment by noahzn** [comment]
No. You only need to set `--height` and `--width`. But I just found the training code doesn't pass the size parameters to construct the model. I have pushed a new commit, and could you update the code?😊

Please let me know if you need more support.

**Comment by 413090531** [comment]
I just saw the modification you made, your modification is very helpful to me, thank you very much for being so careful and responsible. I still have two small questions I want to ask.
1.Lite-mono at 640x192 resolution and without ImageNet pre-training, how many epochs will it take to train the final result?
2.Lite-mono at 1024x320 resolution and with ImageNet pre-training, how many epochs will it take to train the final result?

**Comment by noahzn** [comment]
You are welcome.
1. 35 epochs. I got the best results around epoch 31.
2. 30 epochs. I got the best results around epoch 24. And just as I told you before, please check the results of all the epochs because the training converges quickly.
