### ISSUE TITLE
About the test of the model on Make3D

### ISSUE THREAD

**Issue by 413090531** [noahzn/Lite-Mono#33]
Hello! Only a few days later, I'm here again.
I saw that in the paper, the model trained on the KITTI dataset is tested on the test set of Make3D. The same operation was performed in "Digging into Self-Supervised Monocular Depth Prediction", but I did not find the code for testing on the Make3D test set. I would like to know how this part of the test should be done？My Email is shanwc97@gmail.com.

Looking forward to your reply.  : )

**Comment by noahzn** [comment]
Hi, please check this [link](https://github.com/nianticlabs/monodepth2/issues/89).

**Comment by 413090531** [comment]
Ok, I saw the link, it helped me a lot, I will try to use this code in the link to test, thank you very much!
