### ISSUE TITLE
How to evaluate the lightweight of the model？

### ISSUE THREAD

**Issue by Zhangc0715** [noahzn/Lite-Mono#35]
Good evening, I would like to ask how to calculate FLOPs and speed in this project, can you provide the code for this part?

**Comment by noahzn** [comment]
Hi! Both functions are already in the code. 
You can use [this function](https://github.com/noahzn/Lite-Mono/blob/main/evaluate_depth.py#L22) to calculate the parameters and FLOPs. The library used is `thop`. 
You can use `t1` and `t2` to compute the speed, see [here](https://github.com/noahzn/Lite-Mono/blob/main/evaluate_depth.py#L130).

**Comment by Zhangc0715** [comment]
Thank you for your reply, I wish you a happy life！
