### ISSUE TITLE
Can't distributed training be conducted?

### ISSUE THREAD

**Issue by Xjmengnieer** [noahzn/Lite-Mono#39]
Can't distributed training be conducted?

**Comment by noahzn** [comment]
Hi, the code is based on Monodepth2, which doesn't support multi-GPU training.

**Comment by Xjmengnieer** [comment]
Is there no script for distributed training written, or is it impossible to conduct distributed training itself?

**Comment by Xjmengnieer** [comment]
> Hi, the code is based on Monodepth2, which doesn't support multi-GPU training.

I tried to conduct distributed training, but failed

**Comment by noahzn** [comment]
You can modify the code to support multiple-GPU training. 
Some hints:
https://github.com/nianticlabs/monodepth2/issues/322
https://github.com/nianticlabs/monodepth2/issues/5

**Comment by Xjmengnieer** [comment]
thank you very much!
