### ISSUE TITLE
Can't not find the package "linear_warmup_cosine_annealing_warm_restarts_weight_decay"?

### ISSUE THREAD

**Issue by s20163081161** [noahzn/Lite-Mono#40]
Can't not find the package "linear_warmup_cosine_annealing_warm_restarts_weight_decay"?

**Comment by YubingChan** [comment]
how to deal with this problem? i encountered this issue too.

**Comment by noahzn** [comment]
> how to deal with this problem? i encountered this issue too.

https://github.com/noahzn/Lite-Mono#dependency-installation

**Comment by YubingChan** [comment]
> > how to deal with this problem? i encountered this issue too.
> 
> https://github.com/noahzn/Lite-Mono#dependency-installation

oh, got it, thanks!
