### ISSUE TITLE
self.models_pose["pose_encoder"] or self.models["pose_encoder"]?

### ISSUE THREAD

**Issue by howardchina** [noahzn/Lite-Mono#42]
A small typo I guess.

https://github.com/noahzn/Lite-Mono/blob/286c4ab750ad491f0930791b29e401e4882f20d9/trainer.py#L343

**Comment by noahzn** [comment]
Hi,
Yes, you are correct! 
However, `pose_model_input` is set to `pairs`, so `self.num_pose_frames = 2` and this line of code will never be executed. If you set `pose_model_input=all` you then need to fix this typo. Thank you!

**Comment by howardchina** [comment]
Yes, pairs mode will never call this line.
