### ISSUE TITLE
about pretrain model

### ISSUE THREAD

**Issue by xingjingjie123** [noahzn/Lite-Mono#49]
thank you for answering my previous question ,you code is great.but i don't have the pretrain model ,could you give me the pretrain model .my email is 2941851268@qq.com.

**Comment by noahzn** [comment]
Hi, all the pre-trained models and weights can be downloaded in this repo. https://github.com/noahzn/Lite-Mono#kitti

**Comment by noahzn** [comment]
I am now closing this issue due to no response.
