### ISSUE TITLE
Evaluation of Lite-Mono-8m

### ISSUE THREAD

**Issue by ldkong1205** [noahzn/Lite-Mono#5]
Hi @noahzn, thanks for your great work!

I was trying to evaluate the `lite-mono` family. I am able to test `lite-mono` and `lite-mono-small` but encountered the following error when evaluating on `lite-mono-8m`:

```
Traceback (most recent call last):
  File "/Lite-Mono/evaluate_depth.py", line 223, in <module>
    evaluate(options.parse())
  File "/Lite-Mono/evaluate_depth.py", line 102, in evaluate
    encoder = networks.LiteMono(model=opt.model,
  File "/Lite-Mono/networks/depth_encoder.py", line 384, in __init__
    stage_blocks.append(DilatedConv(dim=self.dims[i], k=3, dilation=self.dilation[i][j], drop_path=dp_rates[cur + j],
IndexError: list index out of range
```

Could you have a look at this? Thanks!

**Comment by ldkong1205** [comment]
> Hi @ldkong1205 , here you go!

Hi @noahzn, thank you so much for your prompt reply! It helps me a lot ~

We are doing robustness probing of monocular depth estimation models and we just found that Lite-Mono is not just more efficient but also more robust than previous work! (Well done 👍🏻)

You can walk through our study from [this](https://github.com/ldkong1205/RoboDepth) page. Meanwhile, we would like to know about Lite-Mono in terms of pertaining. Therefore, is it applicable for you to also release the checkpoints for models trained without ImageNet pertaining? Thanks in advance for your help!

**Comment by noahzn** [comment]
Oh really? I'm very happy to hear that! Thanks!!
Regarding the checkpoints without pretraining I am not sure if I have deleted them or not. I will check and let you know.

**Comment by ldkong1205** [comment]
> Oh really? I'm very happy to hear that! Thanks!! Regarding the checkpoints without pretraining I am not sure if I have deleted them or not. I will check and let you know.

Hi @noahzn, thank you as well. We now have a baseline that has better trade-offs between efficiency and robustness 😄 

For the checkpoints: don't worry, we will try to reproduce them ourselves.

For the robustness benchmark: It would be great if you can supplement a Table in your paper and repository. You can just copy the numbers from our benchmark when comparing. All models evaluated are from public resources or trained with official configurations so that their robustness is directly comparable. Please let me know if you want to know more about this benchmark or if you need some help on this. Thanks!

**Comment by noahzn** [comment]
I finally found the weights for `Lite-Mono` and `Lite-Mono-small`. Unfortunately, I deleted the `Lite-Mono-tiny` weights. 
Here is the [link](https://surfdrive.surf.nl/files/index.php/s/yFgwWmHDQ5L2QY5). Hope it is useful. 

I don't have room to add your table to my camera-ready paper, but I'll copy it to my GitHub Lite-Mono page. Thanks a lot!

**Comment by ldkong1205** [comment]
Thank you very much for your prompt help! Should you have any questions about the benchmark, please let me know at your earliest convenience. Cheers!
