### ISSUE TITLE
frame_ids

### ISSUE THREAD

**Issue by wtpro** [noahzn/Lite-Mono#50]
Hi,

I am confused about the values of frame_ids. Why are they default to [0,-1,1]?

**Comment by noahzn** [comment]
Hi, the target frame is `0`, and the source frame can be either the previous frame `-1` or the next frame `1`.

I wish you all the best at Dragon Boat Festival!

**Comment by wtpro** [comment]
Thanks for the reply! I fully understand the frame_ids now.

Here is another little confusion I had after running your trainer.py.

I want to see how the predicted depth of a single image changes over each epoch during training,
so I saved the predicted depth of the first image from the first minibatch in every epoch 
(in code, `outputs[("depth", 0, 0)][0,...]` ). 

The saved depths do not look like they belong to the same RGB images. Did you randomize the batches for each epoch or augment the data in some way?

Thanks for your time!

**Comment by noahzn** [comment]
Hi, yes, because the dataset is shuffled. You can use `tensorboard --log_dir ./tmp/mytrain` to check the input images and their corresponding generated depth maps.

**Comment by wtpro** [comment]
Thanks a lot!
