### ISSUE TITLE
High CPU usage during training

### ISSUE THREAD

**Issue by rnlee1998** [noahzn/Lite-Mono#52]
When I was training, I found that the cpu usage was high. I tried to improve this problem by reducing num_worker, but I found it didn't work.
![image](https://github.com/noahzn/Lite-Mono/assets/58359878/c97b07e1-bef9-4dd3-8dae-13b8863095bb)

**Comment by noahzn** [comment]
Hi, the data copying between GPU and CPU might be the reason. You might try setting `torch.set_num_threads(num)`, although I haven't tried this.

**Comment by noahzn** [comment]
I'm now closing this issue due to no response. Please feel free to reopen it if you still have questions.
