### ISSUE TITLE
The sq_rel & rmse are too poor other metrics are also not good

### ISSUE THREAD

**Issue by Zora137** [noahzn/Lite-Mono#54]
![8bd90db4211f40b74b1842dce3847f0](https://github.com/noahzn/Lite-Mono/assets/113323676/2dd8d972-6964-4dca-be09-c84ff0369a54)
hi,just like the picture,the performance is too poor. I used the pre-trained model.

and I tried to train and evaluate the monodepth2, I can get results similar to those in these paper as follows.
![image](https://github.com/noahzn/Lite-Mono/assets/113323676/01795472-acb2-4890-b353-b11615d85e84)

can you help me to analyze possible causes？

Thanks.

**Comment by noahzn** [comment]
Hi, I assume you are evaluating the Lite-Mono model (3.1M). Which pre-trained model did you load? It should be [this one](https://surfdrive.surf.nl/files/index.php/s/IK3VtPj6b5FkVnl). Loading the model by setting `--load_weights_folder`.

**Comment by Zora137** [comment]
I download the .zip I wanna ask what --mypretrain should be set and what --load_weights_folder should be set.

This is my command.
![image](https://github.com/noahzn/Lite-Mono/assets/113323676/20ddacb8-a494-4960-9aa8-12358a51ffd3)


I set --mypretrain lite-mono_1024x320 which you offer me but there is the error as follow
![image](https://github.com/noahzn/Lite-Mono/assets/113323676/3377d2fc-ab7c-4918-a814-b5766015f291)

so how many pre-trained model I need ? The link only contains two files encoder.pth and depth.pth.

Thanks for your answer

**Comment by noahzn** [comment]
OK, so you are trying to train the network, not evaluate it.
In this case you don't need to set `--load_weights_folder`. You should download the correct ImageNet pre-trained model. In your case the input size is 640x192 (the default size), so you should use this [pre-trained model](https://surfdrive.surf.nl/files/index.php/s/InMMGd5ZP2fXuia), you should set `--mypretrain xxxx/xxxx.pth`.

**Comment by Zora137** [comment]
hi, I'm sorry to bother you again. The performance is still poor.
The following is the command I try to train the network.
![image](https://github.com/noahzn/Lite-Mono/assets/113323676/674eaff6-472b-4446-a35d-15312c754363)

and this the command I try to evaluate.
![image](https://github.com/noahzn/Lite-Mono/assets/113323676/d0d5daa0-89a9-4854-b27f-a0f9421bb3ab)


and the following is the evaluation result.
![image](https://github.com/noahzn/Lite-Mono/assets/113323676/7cd2cb34-ec93-4747-88f5-96a330d6e8e6)

**Comment by noahzn** [comment]
Hi, your training result is not about "poor" or "good", it is totally "incredible". There must be some big problems in your settings, such as the dataset.

Can you check the tensorboard to see how your training is going?

**Comment by Zora137** [comment]
![3b4481fee84a673fb72f6c47e9e392e](https://github.com/noahzn/Lite-Mono/assets/113323676/8da4a214-f30f-4ad0-bda2-336327dc7cbb)
hi，this is the tensorboard results. Does it mean that there is an error occurred during the evaluation procession?

**Comment by noahzn** [comment]
How many epochs did you train? Your a1/a2/a3 figures only show results in about 10K steps, but your other four metrics are trained on more than 15K steps. Why does this mismatch happen?
Are you using the full KITTI dataset for training? Can you also show the generated images in the tensorboard?

**Comment by Zora137** [comment]
hi，I run tensorboard again and get the result as following.
![image](https://github.com/noahzn/Lite-Mono/assets/113323676/0264e526-f972-4d43-ac7e-3d20d9b1e545)

The following is the command I try to train the network.
![image](https://github.com/noahzn/Lite-Mono/assets/113323676/d8a8dca1-fd34-4fc8-8bd4-beda6a9e4f30)
I trained 30 epoch with the batch size 12.

![image](https://github.com/noahzn/Lite-Mono/assets/113323676/752d36a1-e162-4d55-8128-9f66fe8a444d)
this is the KITTI dataset I download I transformed them into .jpg

**Comment by noahzn** [comment]
Hi, this time the figures look much better, despite some fluctuations. So, I'm wondering if you used a wrong checkpoint last time. Can you evaluate using the checkpoint corresponding to your current tensorboard figures?

**Comment by Zora137** [comment]
sorry，I've tired again.It is still so incredible as the last time.
![19fb80bf2cfdc2b432f5bc057b878b8](https://github.com/noahzn/Lite-Mono/assets/113323676/3b632b64-3543-4e23-81ef-157e7a09aa0f)

**Comment by noahzn** [comment]
I don't know what happened, but obviously, your loaded model is not the one shown in your tensorboard.  In your tensorboard figures, a1, a2, and a3 are all larger than 0.9, but your evaluation gets a1=0.405. I suggest you check carefully if you loaded the wrong model.

**Comment by Zora137** [comment]
hi，I re-download the folowing file，cuz I find the last one I used maybe missing a part
![image](https://github.com/noahzn/Lite-Mono/assets/113323676/d64cbbc7-b591-429e-a6aa-0c09da0e63f1)

But now there is an error following
![image](https://github.com/noahzn/Lite-Mono/assets/113323676/79c352af-3fa1-4505-b936-f6ba4fa4b1a8)
 
Thank you so much for answering.

**Comment by Zora137** [comment]
yes, I've prepared
![image](https://github.com/noahzn/Lite-Mono/assets/113323676/ffe0dfd2-7e27-4282-85a2-c59e935da0a4)

this is the splits I used.
I download eigen_zhou from monodepth2.
Did I use the wrong eigen?
