### ISSUE TITLE
Using NYUv2 dataset to train

### ISSUE THREAD

**Issue by QZZZZZYF** [noahzn/Lite-Mono#56]
If I want to use the NYUv2 dataset for training, how do I need to modify the code?

**Comment by QZZZZZYF** [comment]
Hello，should I prepare NYUDepthV2 datasets following [GLPDepth](https://github.com/vinvino02/GLPDepth) and [BTS](https://github.com/cleinc/bts/tree/master)？
And dataset directory should be:
│nyu_depth_v2/
  ├──official_splits/
  │  ├── test
  │  ├── train
  ├──sync/

**Comment by noahzn** [comment]
Hi, you can arrange the folder structures as you like. I don't know GLPDepth or BTS. As long as you can load the correct images (and ground-truth if you do supervised training), it should work.

**Comment by QZZZZZYF** [comment]
Hello, I encountered an issue with being unable to read data while trying to train using the NYUv2 dataset. Can your colleague share the code if they succeed?

**Comment by noahzn** [comment]
Hi, unfortunately, he is not going to share the code. It's his project, and I was not a co-author of that project.
