### ISSUE TITLE
DistributedDataParallel

### ISSUE THREAD

**Issue by gggxxx1234** [noahzn/Lite-Mono#57]
Hello author, please ask how to achieve multi-GPU training?

**Comment by noahzn** [comment]
Hi. Currently, multi-GPU training is not supported. Someone tried to implement this but encountered some issues ([see this issue](https://github.com/noahzn/Lite-Mono/issues/43)). You are welcome to implement this and share your code (pull requests) if you like.

**Comment by gggxxx1234** [comment]
> Hi. Currently, multi-GPU training is not supported. Someone tried to implement this but encountered some issues ([see this issue](https://github.com/noahzn/Lite-Mono/issues/43)). You are welcome to implement this and share your code (pull requests) if you like.

sorry, I've tried, but I can't.

**Comment by noahzn** [comment]
What problems did you meet? The decoder of the network should be re-implement and don't use the dict type.

**Comment by gggxxx1234** [comment]
> What problems did you meet? The decoder of the network should be re-implemented and don't use the dict type.

Yeah, just deciding whether to change that part or not. You provided a good direction, I try.
