### ISSUE TITLE
Dependency versions

### ISSUE THREAD

**Issue by eltonfss** [noahzn/Lite-Mono#58]
Could you share a requirements.txt containing the dependency versions? (Ex: pytorch version, numpy, ...)

**Comment by noahzn** [comment]
Hi, I have just generated the files on two machines. I cannot guarantee that all the libraries have the same version as when I ran the experiments, but it should not be a problem as PyTorch is the correct version.
[requirements_1.7.1.txt](https://github.com/noahzn/Lite-Mono/files/12143975/requirements_1.7.1.txt)

[requirements_1.12.1.txt](https://github.com/noahzn/Lite-Mono/files/12143976/requirements_1.12.1.txt)

**Comment by eltonfss** [comment]
Thank you @noahzn! I'll try to run the code with those dependencies and let you know if it works.

**Comment by eltonfss** [comment]
Actually, I'm not being able to access the files, have you commited them in some private branch?

**Comment by noahzn** [comment]
> Hi, I have just generated the files on two machines. I cannot guarantee that all the libraries have the same version as when I ran the experiments, but it should not be a problem as PyTorch is the correct version.
> 
> [requirements_1.7.1.txt](https://github.com/noahzn/Lite-Mono/files/12144523/requirements_1.7.1.txt) [requirements_1.12.1.txt](https://github.com/noahzn/Lite-Mono/files/12144525/requirements_1.12.1.txt)

@eltonfss Hi, the files are in my comment. Can you see them?

**Comment by eltonfss** [comment]
I tried opening them but for some reason I'm unable do download:

![image](https://github.com/noahzn/Lite-Mono/assets/4651610/a16ae9ba-42e5-450b-a32f-7bea31b6a02b)

![image](https://github.com/noahzn/Lite-Mono/assets/4651610/3e4cabaf-a69c-4b07-893a-53655af117fd)

**Comment by eltonfss** [comment]
Never mind, I was able to download them using `wget`

![image](https://github.com/noahzn/Lite-Mono/assets/4651610/6f9d92d0-8b07-49c0-b7ee-f620348fd99b)
