### ISSUE TITLE
test_simple.py

### ISSUE THREAD

**Issue by didncd** [noahzn/Lite-Mono#6]
hi, I had a problem when I run test_simple.py. The output is as follows : 
  File "test_simple.py", line 154, in test_simple
    outputs, _ = depth_decoder(features)
ValueError: too many values to unpack (expected 2)

And I change the code to "outputs = depth_decoder(features)", that will no problem. But I wonder if this modification would have an effect on the result？

**Comment by noahzn** [comment]
Hi, thanks for your feedback! Indeed, I changed the output of `depth_decoder.py` but didn't make the corresponding change in `test_simple.py`.

Your change is correct and the result is the same. I have fixed this issue. Thank you!

**Comment by didncd** [comment]
OK, thanks for the reply !
