### ISSUE TITLE
Receive video stream as input

### ISSUE THREAD

**Issue by Arkitect-z** [noahzn/Lite-Mono#62]
Hi, I tried to modify test_simple.py to implement support for input video files for depth prediction, but this doesn't seem to work because PoseNet in the paper predicts from multiple frame images.
Is this correct? How should I modify the code to achieve this or is there any existing code for this?

**Comment by noahzn** [comment]
Hi, you don't need the PoseNet when inferring the model. So, it's possible to take a video as the input.

This [`for` loop](https://github.com/noahzn/Lite-Mono/blob/main/test_simple.py#L140) loads the path of each image and feeds it into the DepthNet. Therefore, you can write your video loading code here and you input each frame of the video.

**Comment by Arkitect-z** [comment]
Thank you for your answer.
