### ISSUE TITLE
x = (x - 0.45) / 0.225

### ISSUE THREAD

**Issue by bonne658** [noahzn/Lite-Mono#63]
what does `x = (x - 0.45) / 0.225` mean in forward function?

**Comment by noahzn** [comment]
Hi, when we pre-trained the model on ImageNet, we normalized the images using `mean = [0.485, 0.456, 0.406]` and `std = [0.229, 0.224, 0.225]`. Therefore, we also need to normalize the images when we train the model on KITTI.

**Comment by noahzn** [comment]
I am now closing this thread due to lack of response.

**Comment by bonne658** [comment]
> Hi, when we pre-trained the model on ImageNet, we normalized the images using `mean = [0.485, 0.456, 0.406]` and `std = [0.229, 0.224, 0.225]`. Therefore, we also need to normalize the images when we train the model on KITTI.

Thanks
