### ISSUE TITLE
How to train this model on my own datasets??

### ISSUE THREAD

**Issue by dreamlychina** [noahzn/Lite-Mono#66]

**Comment by noahzn** [comment]
Hi, you only need sequential images for training. At least, you need to change the [intrinsic](https://github.com/noahzn/Lite-Mono/blob/main/datasets/kitti_dataset.py#L18). You can take a look at this [issue](https://github.com/noahzn/Lite-Mono/issues/56) and it might be helpful.

**Comment by dreamlychina** [comment]
> Hi, you only need sequential images for training. At least, you need to change the [intrinsic](https://github.com/noahzn/Lite-Mono/blob/main/datasets/kitti_dataset.py#L18). You can take a look at this [issue](https://github.com/noahzn/Lite-Mono/issues/56) and it might be helpful.

But I dont have any sequential images.  what should i do to train this model?? could you please give me some device？

**Comment by noahzn** [comment]
You cannot use such self-supervised images if you don't have sequential images. You can just simply use your mobile phone to take videos for training. You need to get the intrinsic of your camera.

**Comment by noahzn** [comment]
I am now closing this issue due to no response.
