### ISSUE TITLE
About model generalization

### ISSUE THREAD

**Issue by puyiwen** [noahzn/Lite-Mono#67]
Hi,I have been doing supervised monocular depth estimation before, but I found that supervision requires the support of a large number of datasets to achieve good generalization. If I use some indoor data for training, I don't know how well the lite-mono model generalizes? Compared with supervised models, will unsupervised models generalize better? Looking forward to your answer.

**Comment by noahzn** [comment]
Hi! It's hard to say. The generalization of a model depends on many aspects. One of the benefits of using a self-supervised method is that it doesn't require ground-truth, and you can fine-tune the model easily on a new dataset.

Lite-Mono has good robustness and it has been chosen as one of the benchmarks of the [RoboDepth Challenge](https://github.com/ldkong1205/RoboDepth) at ICRA this year, but I haven't tested the generalization ability of Lite-Mono on indoor datasets. It's worth a try. There are also some papers on the generalization ability of self-supervised training that you can have a look at.

**Comment by noahzn** [comment]
I am now closing this issue due to no response.
