### ISSUE TITLE
test_simple.py

### ISSUE THREAD

**Issue by XJLeoYu** [noahzn/Lite-Mono#68]
when i tried with python test_simple.py --load_weights_folder xxx/networks --image_path path/to/your/test/image after I put lite-mono-pretrain.pth into the folder networks,the error gose like:
FileNotFoundError: [Errno 2] No such file or directory:encoder.pth
I check the whole project and your other repository like:https://github.com/nianticlabs/monodepth2
I didn't find way to download the encoder.pth,(even if I do find the encoder.pth in your repository of ICCV 2019,it turns out that didn't match the model sructure.
need some help

**Comment by noahzn** [comment]
I am now closing this issue due to no response.
