### ISSUE TITLE
Project3D class definition is correct for cam_points as input?

### ISSUE THREAD

**Issue by DheerajMadda** [noahzn/Lite-Mono#70]
In layers.py at lines 211 to 214:

> def forward(self, points, K, T):
>         P = torch.matmul(K, T)[:, :3, :]
>         cam_points = torch.matmul(P, points)
      
In trainer.py at lines 416 to 419:
> cam_points = self.backproject_depth[source_scale](
>                     depth, inputs[("inv_K", source_scale)])

> pix_coords = self.project_3d[source_scale](
>                     cam_points, inputs[("K", source_scale)], T)

With respect to the above information;
As points are already in camera coordinate system, why they are multiplied by the projection matrix P in Project3D class definition?

**Comment by noahzn** [comment]
Hello, the `Project3D` class is used to project the points onto the image space, and the `BackprojectDepth` class is used to transform a depth map to point clouds.

**Comment by DheerajMadda** [comment]
Got it, thanks!
