### ISSUE TITLE
Do the parameters of the lite-Mono include Posenet?

### ISSUE THREAD

**Issue by breknddone** [noahzn/Lite-Mono#74]
The parameter size of Posenet seems to be more than 10M，do the parameters of the lite-Mono include Posenet?Will Posenet's larger parameter size affect lightweight deployment?

**Comment by noahzn** [comment]
Hi @breknddone, you don't need the PoseNet for inferring a depth map. Therefore, its parameters are not included.

**Comment by breknddone** [comment]
> Hi @breknddone, you don't need the PoseNet for inferring a depth map. Therefore, its parameters are not included.

thanks!can you provide some tutorial on deploying this model to nvida jetson？

**Comment by noahzn** [comment]
> > Hi @breknddone, you don't need the PoseNet for inferring a depth map. Therefore, its parameters are not included.
> 
> thanks!can you provide some tutorial on deploying this model to nvida jetson？

Hi, I don't have this kind of tutorial. You can directly infer the PyTorch model on Jetson or quantize the model based on what you need.

**Comment by breknddone** [comment]
> > > Hi @breknddone, you don't need the PoseNet for inferring a depth map. Therefore, its parameters are not included.
> > 
> > 
> > thanks!can you provide some tutorial on deploying this model to nvida jetson？
> 
> Hi, I don't have this kind of tutorial. You can directly infer the PyTorch model on Jetson or quantize the model based on what you need.

thank u！
