### ISSUE TITLE
How to do pre-training on image-Net？

### ISSUE THREAD

**Issue by vfan26** [noahzn/Lite-Mono#76]
The paper mentioned that pre-training on image-Net can get better results. How is this pre-training done?

**Comment by noahzn** [comment]
Hello, we trained the DepthNet encoder on ImageNet. The last layers of the encoder were modified to allow the network to classify the input image (1000 classes). This is a common practice to create a pre-trained model.

**Comment by vfan26** [comment]
> Hello, we trained the DepthNet encoder on ImageNet. The last layers of the encoder were modified to allow the network to classify the input image (1000 classes). This is a common practice to create a pre-trained model.

thank you for your reply

**Comment by vfan26** [comment]
Is it pre-trained on imageNet-1k?

**Comment by noahzn** [comment]
> Is it pre-trained on imageNet-1k?

Yes.

**Comment by FFDoube** [comment]
Hello Author, I would like to know whether the statement in the paper about not pre-training on ImageNet refers only to DepthEncode, or does it also include the ResNet18 in PoseNet?

**Comment by noahzn** [comment]
> Hello Author, I would like to know whether the statement in the paper about not pre-training on ImageNet refers only to DepthEncode, or does it also include the ResNet18 in PoseNet?

@FFDoube, Hi, this means that only the DepthEncoder is not pre-trained. We always used a pre-trained ResNet18 as PoseNet.
