### ISSUE TITLE
Network inference time problem

### ISSUE THREAD

**Issue by mrwen-hard** [noahzn/Lite-Mono#78]
Hello, thank you for sharing. Is there any code in the test_simple.py file for calculating the inference time of the network on GPU and CPU?How to calculate network inference time?

**Comment by noahzn** [comment]
Hi, you can take a look at [this issue](https://github.com/noahzn/Lite-Mono/issues/55).

**Comment by noahzn** [comment]
Hi @mrwen-hard , `test_simple.py` can predict the depth of a single image. We cannot get a reliable inference time from running the network with `batchsize=1`. Instead, the script `evaluate_depth.py` evaluates both accuracy and speed. The default validation set contains more images, and therefore you can easily test the speed with different batch sizes. 

Imagine if you were to use `test_simple.py` to test the speed of the network with `batchsize=16`, you need to prepare a folder containing at least 16 images. Obviously, it is more convenient to test the speed when evaluating the network. :)

**Comment by noahzn** [comment]
I am closing this issue due to no response.

**Comment by mrwen-hard** [comment]
Thank you for your reply. The previous issue about inference time has been resolved.
