### ISSUE TITLE
How to deploy your model on jetson?

### ISSUE THREAD

**Issue by breknddone** [noahzn/Lite-Mono#79]
Hello！Your paper mentioned that you deployed lite-mono to Jetson Xavier. Can you provide a deployment tutorial?How would I deploy similar models to the Jetson device to compare the performance between models?

**Comment by noahzn** [comment]
Hi @breknddone , I don't have such a tutorial. You can simply infer the PyTorch model on Jetson or quantize the model if needed.

**Comment by breknddone** [comment]
> Hi @breknddone , I don't have such a tutorial. You can simply infer the PyTorch model on Jetson or quantize the model if needed.

thank u.So how to get the **speed evaluation** as your paper when I infer the PyTorch model on Jetson?

**Comment by noahzn** [comment]
You can use the same evaluation [code](https://github.com/noahzn/Lite-Mono/blob/main/evaluate_depth.py#L132). The time of a batch can be calculated by `t2-t1`.

**Comment by breknddone** [comment]
> You can use the same evaluation [code](https://github.com/noahzn/Lite-Mono/blob/main/evaluate_depth.py#L132). The time of a batch can be calculated by `t2-t1`.

Thanks.So you just ran your code on Jetson without deploying it, right?And how to get the FLOPs?

**Comment by noahzn** [comment]
Hi, it's also calculated in that script.
