### ISSUE TITLE
On the depth map and true distance obtained from the model

### ISSUE THREAD

**Issue by yinyang472** [noahzn/Lite-Mono#80]
I would like to know the conversion relationship between the depth map obtained from your model and the actual distance. Can you please let me know

**Comment by noahzn** [comment]
Hi, all the predicted depth values are relative depth. We can not get the actual distance using this monocular method.

**Comment by yinyang472** [comment]
but  the dataset you used  are actual distance

**Comment by noahzn** [comment]
> but the dataset you used are actual distance

Hi, no. We didn't use the ground-truth during training. During evaluation, we use `median scaling` to scale the depth.

**Comment by yinyang472** [comment]
thank you for your answers. by the way  I am trying to convert the the outcome your model give to ground-truth. should I find a References

**Comment by noahzn** [comment]
Yes, you can use median scaling to find a scale ratio and multiply each value by that ratio.

**Comment by yinyang472** [comment]
thank you 🙂
