### ISSUE TITLE
about pretrained model in 1024*320

### ISSUE THREAD

**Issue by JiaoPanpan** [noahzn/Lite-Mono#85]
hi, dear noahzn, I am so excited about your outstanding work that I wanna exploring more. Do you have the plan to release the pretrained models whose input-size is 1024*320? 

Looking forward to your reply, thanks~

**Comment by noahzn** [comment]
Hi, thanks for your interest in our work. The pre-trained model you require can be found in the first table in this repo.

**Comment by JiaoPanpan** [comment]
I got it. 
Thanks a lot!!
