### ISSUE TITLE
splits

### ISSUE THREAD

**Issue by 757787182** [noahzn/Lite-Mono#87]
Could you tell me the folders beachmark, eigen, eigen_batchmark, eigen_full, and eigen_zhou in the splits folder of Monodepth2 code mean, Could you tell me the file split did you use for your model training, and could you tell me  your choice of resent network and mask? It would be better if you could tell me your parameter choices. This is very important to me, thank you a lot.

**Comment by noahzn** [comment]
Hi, I used `eigen_zhou` for training and evaluation. The split `eigen` is used for training. All the necessary parameters are defined in [options.py](https://github.com/noahzn/Lite-Mono/blob/main/options.py)
