### ISSUE TITLE
use_pos_embd_xca=[True, False, False]

### ISSUE THREAD

**Issue by jilner** [noahzn/Lite-Mono#88]
Hello, why only the first LGFI module uses location coding?

**Comment by noahzn** [comment]
Hi, we found that the positional encoding did not play an important role in this task. Therefore, this setting is optional.

**Comment by noahzn** [comment]
Hi, we found that the positional encoding did not play an important role in this task. Therefore, this setting is optional.

**Comment by noahzn** [comment]
I am closing this issue due to no response.
