### ISSUE TITLE
Pre-training code

### ISSUE THREAD

**Issue by mrwen-hard** [noahzn/Lite-Mono#89]
Thank you for sharing. Can you please give me a package project code pre-trained on the ImageNet dataset?My email is 185425751@qq.com. Thank you!

**Comment by noahzn** [comment]
Sent.

**Comment by mrwen-hard** [comment]
OK, I have received it, thank you!

**Comment by vfan26** [comment]
I also want a copy of the pre-trained code. Can you send me one?My email is 517130415@qq.com. Thank you!

**Comment by mrwen-hard** [comment]
> I also want a copy of the pre-trained code. Can you send me one?My email is [517130415@qq.com](mailto:517130415@qq.com). Thank you!

Okay, can I add your WeChat account?

**Comment by vfan26** [comment]
> > I also want a copy of the pre-trained code. Can you send me one?My email is [517130415@qq.com](mailto:517130415@qq.com). Thank you!
> 
> Okay, can I add your WeChat account?I have a question I want to discuss with you.

Sent to your email

**Comment by mrwen-hard** [comment]
> > > I also want a copy of the pre-trained code. Can you send me one?My email is [517130415@qq.com](mailto:517130415@qq.com). Thank you!
> > 
> > 
> > Okay, can I add your WeChat account?I have a question I want to discuss with you.
> 
> Sent to your email

QQ mailbox cannot be logged in at the moment. I will send you the pre-training code tomorrow.

**Comment by vfan26** [comment]
> > > > I also want a copy of the pre-trained code. Can you send me one?My email is [517130415@qq.com](mailto:517130415@qq.com). Thank you!
> > > 
> > > 
> > > Okay, can I add your WeChat account?I have a question I want to discuss with you.
> > 
> > 
> > Sent to your email
> 
> QQ mailbox cannot be logged in at the moment. I will send you the pre-training code tomorrow.

My wechat account is wu517130415

**Comment by Shaw-Way** [comment]
I want a copy of pre-training code, too. My email xiao1434483173@outlook.com. Thank you in advance!

**Comment by noahzn** [comment]
Hi @Shaw-Way , I have sent you a copy.

**Comment by Shaw-Way** [comment]
> Hi @Shaw-Way , I have sent you a copy.

Thank you so much! Have a nice day.

**Comment by DakotaFrico33** [comment]
Thank you for your research work @noahzn. I would like to reproduce your work, so could you please send me the code for pre-training the DepthNet on ImageNet dataset? My email is [m11007805@gapps.ntust.edu.tw](mailto:m11007805@gapps.ntust.edu.tw). Thank you for your help!
