### ISSUE TITLE
Another lightweight depth model RM-Depth (2.97M) in CVPR 2022

### ISSUE THREAD

**Issue by twhui** [noahzn/Lite-Mono#9]
Just want to remind that there actually exists another lightweight depth model RM-Depth (CVPR 2022). It has a model size 2.97M while it achieves AbsRel = 0.107 on KITTI and AbsRel = 0.090 on Cityscapes testing sets. Unfortunately, it is not cited.

**Comment by noahzn** [comment]
Hi, thanks for the information. It is a pity that we did not notice the existence of this paper.
