### ISSUE TITLE
ImageNet dataset

### ISSUE THREAD

**Issue by mrwen-hard** [noahzn/Lite-Mono#90]
Could you please provide the Lite-mono pre-trained ImageNet dataset?

**Comment by noahzn** [comment]
Hi, I can't share the dataset because I don't have the copyright. You can download ImageNet from their official website.

**Comment by mrwen-hard** [comment]
Which ImageNet dataset should I download? After downloading, can I unzip it and use it? No other operations required?

**Comment by noahzn** [comment]
ImageNet 2012. You need to extract the training and val sets.

**Comment by noahzn** [comment]
I am closing this issue due to no response.
