### ISSUE TITLE
make3d_test_files.txt

### ISSUE THREAD

**Issue by Jamesgender** [noahzn/Lite-Mono#91]
Hello. I want to evaluate your code on make3d dataset. And the monodepth2 evaluate code used 'make3d_test_files.txt'. Can you share your txt file for easier evaluation?
Thank you!

**Comment by noahzn** [comment]
Hi, I didn't use 'make3d_test_files.txt'. I downloaded the dataset from [here](http://make3d.cs.cornell.edu/data.html).

**Comment by Jamesgender** [comment]
So your evaluate code didn't have the 'make3d_test_files.txt'? Can you share your evaluate code?

**Comment by Jamesgender** [comment]
I am already finished the code. Thanks a lot
