### ISSUE TITLE
what is the difference between the {encoder.pth, depth.pth} and lite-mono-pretrain.pth

### ISSUE THREAD

**Issue by renyuanzhe** [noahzn/Lite-Mono#93]

**Comment by noahzn** [comment]
`lite-mono-pretrain.pth` saves the weights of the encoder pre-trained on ImageNet. Based on these pre-trained weights, we then trained the network on KITTI and got `encoder.pth` and `depth.pth`.

**Comment by renyuanzhe** [comment]
@noahzn Is encoder.pth the trained version of lite-mono-pretrain.pth?

**Comment by noahzn** [comment]
Yes, you could say that.

**Comment by renyuanzhe** [comment]
@noahzn thank you!

**Comment by LLLYLong** [comment]
> `lite-mono-pretrain.pth` saves the weights of the encoder pre-trained on ImageNet. Based on these pre-trained weights, we then trained the network on KITTI and got `encoder.pth` and `depth.pth`.
@noahzn Hi author, once again I'm bothering you， can you provide a copy of the weights of the encoder and decoder that have been trained, I only want to use them for inference, and the weights that I have trained myself do not give the best results!

**Comment by LLLYLong** [comment]
> `lite-mono-pretrain.pth` saves the weights of the encoder pre-trained on ImageNet. Based on these pre-trained weights, we then trained the network on KITTI and got `encoder.pth` and `depth.pth`.

@noahzn Hi author, once again I'm bothering you， can you provide a copy of the weights of the encoder and decoder that have been trained, I only want to use them for inference, and the weights that I have trained myself do not give the best results!

**Comment by noahzn** [comment]
@LLLYLong , hi, all the weights can be downloaded in the repo. Please check README.md carefully. And, please don't reply to a closed issue next time. THanks.
