### ISSUE TITLE
The weights only pretrained with ImageNet before trained with KITTI

### ISSUE THREAD

**Issue by GenkiK** [noahzn/Lite-Mono#94]
Hi, thanks for your sharing your great work! Could you share the weights pretrained with only ImageNet, not KITTI?

**Comment by noahzn** [comment]
Hi, the pre-trained weights are already shared. In the table there is one column called `ImageNet Pretrained`, and you can click `yes` with a link to download the weights.

**Comment by GenkiK** [comment]
I got it. Thanks for your quick reply!
