### ISSUE TITLE
About train_files.txt

### ISSUE THREAD

**Issue by chaoying0115** [noahzn/Lite-Mono#97]
您好 非常感谢您出色的工作 我在复现代码过程中出现问题

1、若要基于kitti训练模型，请问是从ImageNet Pretrained “yes"处下载模型权重，然后执行训练命令？
2、如果是，在训练过程中报错， File "/data/ccy/project/Lite-Mono-main/utils.py", line 11, in readlines
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/ccy/project/Lite-Mono-main/splits/eigen_zhou/train_files.txt'
即找不到train_files.txt，请问该如何解决？目前在文件中仅有/data/ccy/project/Lite-Mono-main/splits/eigen/test_files.txt文件

非常期待您们的回复 谢谢~

**Comment by chaoying0115** [comment]
我发现执行python train.py --data_path /data/ccy/project/Lite-Mono-main/kitti_data/  --model_name mytrain --num_epochs 30 --batch_size 6 --mypretrain /data/ccy/project/Lite-Mono-main/lite-mono-pretrain.pth  --lr 0.0001 5e-6 31 0.0001 1e-5 31
命令时，不止会出现train_files.txt的缺失，是eigen_zhou整个文件的都不存在，请问能否提供一下eigen_zhou的文件或者下载地址？非常感谢~

**Comment by noahzn** [comment]
Hi, 
1, Yes;
2. Please download and unzip the KITTI dataset.
